### ISSUE TITLE
Corsair Link support

### ISSUE THREAD

**Issue by deivater** [antonpup/Aurora#904] opened 2017-12-09 16:30 UTC
I know, there is thread already, but it is closed :)
Support for corsair link would be sick. Can´t imagine, how nice it will looks, with my Corsair node pro and RGB Fans. If this feature will be added, I will send you a paypal donation, because this is the feature, I´m waiting for :)  Aurora is awesome.
Thank you for your work.

Edit: that last bullet side doesn´t work.
I would like to try out some cool profiles.

best regards 
Kevin

**Comment by deivater** [comment] 2017-12-26 00:03
http://forum.corsair.com/forums/showthread.php?t=120092

**Comment by simon-wh** [comment] 2018-01-20 00:16
Duplicate of #546

**Closed by simon-wh** 2018-01-20 00:16 UTC
