### ISSUE TITLE
Rocket League integration

### ISSUE THREAD

**Issue by TrickyTom** [antonpup/Aurora#1115] opened 2018-05-30 19:40 UTC
### What are you experiencing an issue with?

- [X ] Aurora
- [X ] Rocket League, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

###Problem

I only installed Aurora today. I tried to use it with Rocket League with the default settings and it didn't work as intended, it just showed a complete blue keyboard no matter what team/boost level. It should have changed colour between teams etc. I know rocket league just had an update yesterday, so that might be the issue.

### How often does this problem occur?

This problem occurs... Every time I've tried it (3 or 4) only today.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. launching rocket league
2. ???
3. profit

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
I only installed it today

**Comment by simon-wh** [comment] 2018-05-30 19:52
Duplicate of #185

**Closed by simon-wh** 2018-05-30 19:52 UTC
