### ISSUE TITLE
Overwatch Lighting going crazy (G910)

### ISSUE THREAD

**Issue by Davos234** [antonpup/Aurora#2031] opened 2020-05-22 09:37 UTC
### Expected Behaviour
The color of my keyboard lighting should change based on the selected hero and actions done in the game

### Actual Behaviour
The whole keyboard is just flickering like crazy as shown here:
![keyboard](https://user-images.githubusercontent.com/65761945/82653549-ac7cca00-9c1f-11ea-861d-380572049522.gif)

### Reproduction steps
The problem starts as soon as I get to the hero selection and continues while controling a hero.

### Frequency
So far it happened every time.

### Aurora Version:
v0.7.2

### Previously an Issue?
No

**Comment by diogotr7** [comment] 2020-05-22 10:59
Duplicate of #1960

**Closed by diogotr7** 2020-05-22 10:59 UTC
Labels: Type: Bug
