### ISSUE TITLE
Can't get Mirror's Edge Effects to work on Corsair K70

### ISSUE THREAD

**Issue by FTWOblivion** [antonpup/Aurora#1049] opened 2018-04-02 08:48 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
Should have effects and work automatically like every other LG RGB app

### Actual behavior:
Keyboard just shows white, doesn't change with effects like it should

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:

1. Starting Mirror's Edge Catalyst
2. K70 Corsair

### What is the version of Aurora you are experiencing this issue with?
Newest

### Does the previous version of Aurora have this issue?
Not sure

**Comment by simon-wh** [comment] 2018-05-05 16:27
Duplicate of #1052

**Closed by simon-wh** 2018-05-05 16:27 UTC
