### ISSUE TITLE
Logitech G910 Spark Absolutely no Working on Overwatch

### ISSUE THREAD

**Issue by WhiteWidowFR** [antonpup/Aurora#1663] opened 2019-08-20 07:03 UTC
### Expected Behaviour
Aurora Work but No Light with Overwatch :'(

### Actual Behaviour
When i launch the game, i try as administrator too = same trouble, no light.
For the rest Aurora is working.
I already pass 3h on it, uninstall & reinstall C++ & did everything i find in Github

### Reproduction steps
I have to force DLL to work on my logitech, device correctly accepted,
i run in propreties as administrator, nothing when the game launch

### Frequency
Everytime

### Aurora Version:
0.6.4b

### Previously an Issue?
1st time i use it

I really take litterally 3x 60min, try more than 10 restart of computer after reinstalling C++
The C++ 2015 is not visible after correct installation. Only 2017 visible in my uninstall board.
The first time i try to install Aurora, i have a trouble & failed to instal C++2015
I did a uninstall of 2015-2019 C++ by security.
Everything normaly work fine except "wrapper"

Really gentle to help me if you can.

**Comment by diogotr7** [comment] 2019-08-20 11:47
Duplicate of #1570

**Comment by diogotr7** [comment] 2019-08-20 11:48
We have to change our approach to support overwatch, it will hopefully be merged soon. Until then I've posted instructions in auroras discord server.

**Closed by diogotr7** 2019-08-20 11:48 UTC
Labels: bug

**Comment by iFrez** [comment] 2019-08-31 18:42
Logitech G810 and Aurora v0.7.0-rc1 still have issue.
