### ISSUE TITLE
GTX Strix sync

### ISSUE THREAD

**Issue by ferpart** [antonpup/Aurora#701] opened 2017-07-31 19:11 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Sync with Gtx Strix graphic cards)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
RGB Graphics cards should be able to be synced up as it would be a nice addition

### Actual behavior:
No sync capabilities as of just yet

### How often does this problem occur?

This problem occurs... (It is't implemented yet)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-07-31 19:18
I think you're talking about Asus Aura(?). If so, duplicate of #546

**Closed by simon-wh** 2017-07-31 19:18 UTC
