### ISSUE TITLE
New Feature philips HUE

### ISSUE THREAD

**Issue by ced455** [antonpup/Aurora#1096] opened 2018-05-13 17:23 UTC
Hello

I don't know if it's possible but can you link your software with a philips HUE bridge to change the light accordingly to a event (like red blinking when bomb is paused in CS:GO)

I can already contrtol my hue light with the soft aura from asus and it work fine. 

 I know it sounds crazy but it would be SUPER cool.

Many Thanks

**Comment by BUCKFAE** [comment] 2018-05-16 12:26
I'd die to see philips hue support added to this.

**Comment by JoshWobbles** [comment] 2018-05-26 13:26
Or at least IFTTT support, then it could control more than just HUE.

**Comment by JoshWobbles** [comment] 2018-05-26 13:28
It does mention scripting support, if the scripting is robust enough to make a http request then IFTTT and thus HUE may already work (with some trickery).

**Comment by simon-wh** [comment] 2018-05-26 16:06
Duplicate of #358

**Closed by simon-wh** 2018-05-26 16:06 UTC
