### ISSUE TITLE
Add G810 Media, caps lock, num lock, scroll lock, light on/off and gaming buttons

### ISSUE THREAD

**Issue by argente69** [antonpup/Aurora#720] opened 2017-08-07 19:31 UTC
Hello developers, adding these top buttons of the G810 would make the keyboard appear a way better, it always shines white when Aurora is on, and they are RGB

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Here are the highlighted keys:
http://i.imgur.com/g74UVWB.jpg

**Comment by simon-wh** [comment] 2017-08-07 20:00
Duplicate of #711 see explanation there.

**Closed by simon-wh** 2017-08-07 20:00 UTC

**Comment by argente69** [comment] 2017-08-07 20:24
but there's something at the LED Library:
        G_1                     = 0xFFF1,
        G_2                     = 0xFFF2,
        G_3                     = 0xFFF3,
        G_4                     = 0xFFF4,
        G_5                     = 0xFFF5,
        G_6                     = 0xFFF6,
        G_7                     = 0xFFF7,
        G_8                     = 0xFFF8,
        G_9                     = 0xFFF9,
        G_LOGO                  = 0xFFFF1,
        G_BADGE                 = 0xFFFF2
![image](https://user-images.githubusercontent.com/29031093/29044108-4636b804-7b94-11e7-8e44-3cdcef578e4f.png)

**Comment by simon-wh** [comment] 2017-08-07 20:39
Yes? They're the G keys and the logo and badge leds

**Comment by argente69** [comment] 2017-08-07 20:42
oh, i though it was the buttons because my keyboard doesn't have them, sorry
