### ISSUE TITLE
Numpad Lighting Issues - Masterkeys L

### ISSUE THREAD

**Issue by Tehu-Tehu** [antonpup/Aurora#809] opened 2017-09-27 03:38 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Masterkeys L RGB Red Switch)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
1. Pressing Numpad's Enter key should light up when pressed while an interactive layer is active
2. Numpad 4,5 and 6 should react to lighting like any other key

### Actual behavior:
1. Pressing Numpad's Enter key lights up the normal Enter key instead.
2. Numpad 4,5 and 6 are acting as if you're pressing 1 key to the right on the same row of keys (video included)

### How often does this problem occur?

This problem occurs Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. For the Numpad's Enter key - make any kind of interactive layer and press it
2. For the Numpad's 4,5 and 6 row make an interactive layer and press on each one of them

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
No idea , i just got that keyboard and downloaded aurora from the main site..

### Please include any logs, screenshots, or files that are related to this issue:

Logs -> https://pastebin.com/zvWFp2sa , https://pastebin.com/6qNYXcWY
Video -> https://i.imgur.com/ZFJduaA.mp4

**Comment by simon-wh** [comment] 2017-09-27 13:48
Numpad issue is a duplicate of #549.
The enter key issue has not been previously known, could you try [the latest development release](https://github.com/antonpup/Aurora/releases)?

**Comment by Tehu-Tehu** [comment] 2017-09-27 13:57
i did and the enter key got fixed , but the numpad problem got reversed , now 6 lights up 5 - and i noticed another problem on the latest development release build , the lighting effects arent registering as fast as 0.6.0, if i spam a key in an interactive layer theres a short delay before the lighting effect will register again

**Comment by simon-wh** [comment] 2017-09-27 16:51
The thing with the interactive layer is intentional, it is to prevent high cpu usage when using a macro that spams a particular key. The numpad issue is still #549 so I'm going to close this.

**Closed by simon-wh** 2017-09-27 16:51 UTC
Labels: bug, information needed
