### ISSUE TITLE
Coolermaster Pro L numpad key not lighting up at all

### ISSUE THREAD

**Issue by DarrenBell** [antonpup/Aurora#686] opened 2017-07-25 08:43 UTC
### What are you experiencing an issue with?

- [] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X ] Aurora Lighting issue
- [X ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X ] Device issue
- [X ?] Other, (Fill in another type of issue here)

### Expected behavior:

Any lighting setting which fills the keyboard should light up all keys on the keyboard.

### Actual behavior:

Selecting key 4 on the numpad to light up in any setting does not light up at all.  It does however work in the Coolermaster Software so it is not a faulty LED.

### How often does this problem occur?

This problem occurs... always from testing

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora software.
2. Set any lighting that requires freestyle and drag over whole keyboard (in layers).
3. Problem appears on keypad number 4.

### What is the version of Aurora you are experiencing this issue with?

My version is... beta 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

I can take a photo if required.

**Comment by simon-wh** [comment] 2017-07-25 09:01
Duplicate of #549

**Closed by simon-wh** 2017-07-25 09:01 UTC
