### ISSUE TITLE
Aurora Not Support Logitech G Pro Keyboard

### ISSUE THREAD

**Issue by Lauvre** [antonpup/Aurora#1026] opened 2018-03-16 15:06 UTC
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Aurora doesn't support logitech g pro keyboard)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

**Comment by simon-wh** [comment] 2018-03-16 20:37
Duplicate of #902

**Closed by simon-wh** 2018-03-16 20:37 UTC
