### ISSUE TITLE
Asus Aura Support

### ISSUE THREAD

**Issue by Spe3dy123** [antonpup/Aurora#1345] opened 2018-11-25 20:50 UTC
Would it be possible to add Asus Aura support?
It has an SDK: https://www.asus.com/campaign/aura/us/SDK.html

**Comment by diogotr7** [comment] 2018-11-25 20:52
Some users are working on this. 

If you want to help test and discuss it would be helpful if you join our discord. There's a link in the main website.

**Comment by simon-wh** [comment] 2019-01-21 16:06
Duplicate of #546

**Closed by simon-wh** 2019-01-21 16:06 UTC
