### ISSUE TITLE
Masterkeys Pro L Mapping Issues

### ISSUE THREAD

**Issue by JakAttk123** [antonpup/Aurora#658] opened 2017-07-17 20:52 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
On the Coolermaster Masterkeys Pro L, all of the numpad lights and well as p1-p4 should light up and respond appropriately to effects.  

### Actual behavior:
Numpad 4 does not light up, and it's lights effect numpad 5.  None of the profile keys light up and the lighting effects for p4 effect the pause key.  

### How often does this problem occur?

This problem occurs... Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Using Masterkeys Pro L
2. Apply lighting to all these keys

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
I do not know if other versions has this issue.

**Comment by simon-wh** [comment] 2017-07-17 20:57
Duplicate of #549

**Closed by simon-wh** 2017-07-17 20:57 UTC
