### ISSUE TITLE
Aurora will not work past initial start up.

### ISSUE THREAD

**Issue by supernintendo64** [antonpup/Aurora#1287] opened 2018-10-03 02:48 UTC
Yesterday I installed Aurora and it worked fine after I followed the instructions to set it up for Logitech Gaming Software, but then later I tried playing Overwatch and the lighting profiles would not work anymore. Whenever I restart Aurora, I could select a profile and it would work, but as soon as I close it and reopen it, it won't work anymore. I'm using a Logitech G910 and a Logitech G502.

EDIT: I discovered that I can fix the problem by turning on the desktop profile and restarting the program. This is still a pretty glaring bug though. I revised my reproduction instructions to reflect this.

### Expected behavior:
Lighting profiles should work while Aurora is running.

### Actual behavior:
Keyboard is stuck on default profile even though Aurora is supposed to override it.

### How often does this problem occur?
Every time I try to use Aurora after closing it for the first time after installing.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Aurora
2. Set it up properly
3. Disable desktop profile
4. Close Aurora
5. Re-open Aurora

### What is the version of Aurora you are experiencing this issue with?
v0.6.3

### Does the previous version of Aurora have this issue?
I don't know. This was the first version I installed.

### Please include any logs, screenshots, or files that are related to this issue:

INITIAL STARTUP:

[INFO] 21:34:04: 
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 4
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.3
========================================

[INFO] 21:34:04: Loading Configuration
[INFO] 21:34:05: Loading Plugins
[INFO] 21:34:05: Loading KB Layouts
[INFO] 21:34:05: Loading Input Hooking
[INFO] 21:34:05: Loading Applications
[INFO] 21:34:07: Loading Device Manager
[INFO] 21:34:54: Device, Logitech, was initialized
[ERROR] 21:34:54: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:34:54: Device, Corsair, was not initialized
[ERROR] 21:34:54: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:34:54: Device, Razer, was not initialized
[ERROR] 21:34:54: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:34:54: Device, Roccat, was not initialized
[ERROR] 21:34:54: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:34:54: Device, Clevo Keyboard, was not initialized
[INFO] 21:34:55: No Cooler Master devices successfully Initialized!
[INFO] 21:34:55: Device, Cooler Master, was not initialized
[ERROR] 21:34:55: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:34:55: Device, SteelSeries, was not initialized
[INFO] 21:34:55: Device, SteelSeriesHID, was not initialized
[INFO] 21:34:55: No Wooting devices successfully Initialized!
[INFO] 21:34:55: Device, Wooting, was not initialized
[INFO] 21:34:55: Device, LightFX, was not initialized
[INFO] 21:34:55: Starting GameStateListener
[INFO] 21:34:55: Retrying Device Initialization
[ERROR] 21:34:55: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:34:55: Device, Corsair, was not initialized
[ERROR] 21:34:55: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:34:55: Device, Razer, was not initialized
[ERROR] 21:34:55: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:34:55: Device, Roccat, was not initialized
[INFO] 21:34:55: Listening for game integration calls...
[INFO] 21:34:55: Loading ResourceDictionaries...
[ERROR] 21:34:55: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:34:55: Device, Clevo Keyboard, was not initialized
[INFO] 21:34:55: No Cooler Master devices successfully Initialized!
[INFO] 21:34:55: Device, Cooler Master, was not initialized
[ERROR] 21:34:55: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:34:55: Device, SteelSeries, was not initialized
[INFO] 21:34:55: [IPCServer] Pipe created 2348279
[INFO] 21:34:55: [AuroraCommandsServerIPC] Pipe created 61669314
[INFO] 21:34:55: Device, SteelSeriesHID, was not initialized
[INFO] 21:34:55: No Wooting devices successfully Initialized!
[INFO] 21:34:55: Device, Wooting, was not initialized
[INFO] 21:34:55: Device, LightFX, was not initialized
[INFO] 21:34:56: Loaded ResourceDictionaries
[INFO] 21:34:56: Loading ConfigUI...
[DEBUG] 21:34:56: Trying to get game path for: 570
[DEBUG] 21:34:56: Trying to get game path for: 730
[DEBUG] 21:34:57: Trying to get game path for: 219150
[DEBUG] 21:34:57: Trying to get game path for: 257510
[DEBUG] 21:34:57: Trying to get game path for: 209870
[DEBUG] 21:34:57: Trying to get game path for: 49470
[DEBUG] 21:34:57: Trying to get game path for: 241930
[DEBUG] 21:34:57: Trying to get game path for: 41070
[DEBUG] 21:34:57: Trying to get game path for: 270450
[DEBUG] 21:34:57: Trying to get game path for: 200510
[DEBUG] 21:34:57: Trying to get game path for: 43160
[DEBUG] 21:34:57: Trying to get game path for: 239140
[DEBUG] 21:34:57: Trying to get game path for: 200010
[DEBUG] 21:34:57: Trying to get game path for: 232090
[INFO] 21:35:00: Retrying Device Initialization
[ERROR] 21:35:00: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:35:00: Device, Corsair, was not initialized
[ERROR] 21:35:00: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:35:00: Device, Razer, was not initialized
[ERROR] 21:35:00: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:35:00: Device, Roccat, was not initialized
[ERROR] 21:35:00: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:35:00: Device, Clevo Keyboard, was not initialized
[INFO] 21:35:00: No Cooler Master devices successfully Initialized!
[INFO] 21:35:00: Device, Cooler Master, was not initialized
[ERROR] 21:35:00: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:35:00: Device, SteelSeries, was not initialized
[INFO] 21:35:00: Device, SteelSeriesHID, was not initialized
[INFO] 21:35:00: No Wooting devices successfully Initialized!
[INFO] 21:35:00: Device, Wooting, was not initialized
[INFO] 21:35:00: Device, LightFX, was not initialized
[INFO] 21:35:05: Retrying Device Initialization
[ERROR] 21:35:05: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:35:05: Device, Corsair, was not initialized
[ERROR] 21:35:05: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:35:05: Device, Razer, was not initialized
[ERROR] 21:35:05: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:35:05: Device, Roccat, was not initialized
[ERROR] 21:35:05: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:35:05: Device, Clevo Keyboard, was not initialized
[INFO] 21:35:05: No Cooler Master devices successfully Initialized!
[INFO] 21:35:05: Device, Cooler Master, was not initialized
[ERROR] 21:35:05: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:35:05: Device, SteelSeries, was not initialized
[INFO] 21:35:05: Device, SteelSeriesHID, was not initialized
[INFO] 21:35:05: No Wooting devices successfully Initialized!
[INFO] 21:35:05: Device, Wooting, was not initialized
[INFO] 21:35:05: Device, LightFX, was not initialized
[INFO] 21:35:18: Device, Logitech, was shutdown
[INFO] 21:35:19: Device, Logitech, was initialized
[ERROR] 21:35:19: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:35:19: Device, Corsair, was not initialized
[ERROR] 21:35:19: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:35:19: Device, Razer, was not initialized
[ERROR] 21:35:19: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:35:19: Device, Roccat, was not initialized
[ERROR] 21:35:19: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:35:19: Device, Clevo Keyboard, was not initialized
[INFO] 21:35:19: No Cooler Master devices successfully Initialized!
[INFO] 21:35:19: Device, Cooler Master, was not initialized
[ERROR] 21:35:19: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:35:19: Device, SteelSeries, was not initialized
[INFO] 21:35:19: Device, SteelSeriesHID, was not initialized
[INFO] 21:35:19: No Wooting devices successfully Initialized!
[INFO] 21:35:19: Device, Wooting, was not initialized
[INFO] 21:35:19: Device, LightFX, was not initialized
[INFO] 21:35:23: Device, Logitech, was shutdown
[INFO] 21:35:56: Device, Logitech, was initialized
[ERROR] 21:35:56: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:35:56: Device, Corsair, was not initialized
[ERROR] 21:35:56: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:35:56: Device, Razer, was not initialized
[ERROR] 21:35:56: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:35:56: Device, Roccat, was not initialized
[ERROR] 21:35:56: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:35:56: Device, Clevo Keyboard, was not initialized
[INFO] 21:35:56: No Cooler Master devices successfully Initialized!
[INFO] 21:35:56: Device, Cooler Master, was not initialized
[ERROR] 21:35:56: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:35:56: Device, SteelSeries, was not initialized
[INFO] 21:35:56: Device, SteelSeriesHID, was not initialized
[INFO] 21:35:56: No Wooting devices successfully Initialized!
[INFO] 21:35:56: Device, Wooting, was not initialized
[INFO] 21:35:56: Device, LightFX, was not initialized
[INFO] 21:35:57: [IPCServer] Pipe connection established
[INFO] 21:36:14: Unknown Wrapper Command: 
[INFO] 21:36:14: [IPCServer] Pipe connection lost
[INFO] 21:36:14: [IPCServer] Pipe created 19347067
[INFO] 21:36:15: Device, Logitech, was shutdown

STARTUP AFTER THAT:

[INFO] 21:45:26: 
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 4
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.3
========================================

[INFO] 21:45:26: Loading Configuration
[INFO] 21:45:26: Loading Plugins
[INFO] 21:45:26: Loading KB Layouts
[INFO] 21:45:27: Loading Input Hooking
[INFO] 21:45:27: Loading Applications
[INFO] 21:45:28: Loading Device Manager
[INFO] 21:45:28: Device, Logitech, was initialized
[ERROR] 21:45:28: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:45:28: Device, Corsair, was not initialized
[INFO] 21:45:28: Device, Logitech, was shutdown
[ERROR] 21:45:28: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:45:28: Device, Razer, was not initialized
[ERROR] 21:45:28: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:45:28: Device, Roccat, was not initialized
[ERROR] 21:45:28: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:45:28: Device, Clevo Keyboard, was not initialized
[INFO] 21:45:28: No Cooler Master devices successfully Initialized!
[INFO] 21:45:28: Device, Cooler Master, was not initialized
[ERROR] 21:45:28: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:45:28: Device, SteelSeries, was not initialized
[INFO] 21:45:28: No Wooting devices successfully Initialized!
[INFO] 21:45:28: Device, Wooting, was not initialized
[INFO] 21:45:28: Device, LightFX, was not initialized
[INFO] 21:45:28: Starting GameStateListener
[INFO] 21:45:28: Retrying Device Initialization
[INFO] 21:45:28: Device, Logitech, was initialized
[ERROR] 21:45:28: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:45:28: Device, Corsair, was not initialized
[ERROR] 21:45:28: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:45:28: Device, Razer, was not initialized
[ERROR] 21:45:28: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:45:28: Device, Roccat, was not initialized
[INFO] 21:45:28: Listening for game integration calls...
[INFO] 21:45:28: Loading ResourceDictionaries...
[ERROR] 21:45:28: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:45:28: Device, Clevo Keyboard, was not initialized
[INFO] 21:45:28: No Cooler Master devices successfully Initialized!
[INFO] 21:45:28: Device, Cooler Master, was not initialized
[ERROR] 21:45:28: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:45:28: Device, SteelSeries, was not initialized
[INFO] 21:45:28: No Wooting devices successfully Initialized!
[INFO] 21:45:28: Device, Wooting, was not initialized
[INFO] 21:45:28: [IPCServer] Pipe created 49538252
[INFO] 21:45:28: [AuroraCommandsServerIPC] Pipe created 21647132
[INFO] 21:45:28: Device, LightFX, was not initialized
[INFO] 21:45:28: Loaded ResourceDictionaries
[INFO] 21:45:28: Loading ConfigUI...
[INFO] 21:45:28: Device, Logitech, was shutdown
[INFO] 21:45:33: Retrying Device Initialization
[INFO] 21:45:33: Device, Logitech, was initialized
[ERROR] 21:45:33: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:45:33: Device, Corsair, was not initialized
[ERROR] 21:45:33: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:45:33: Device, Razer, was not initialized
[ERROR] 21:45:33: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:45:33: Device, Roccat, was not initialized
[ERROR] 21:45:33: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:45:33: Device, Clevo Keyboard, was not initialized
[INFO] 21:45:33: No Cooler Master devices successfully Initialized!
[INFO] 21:45:33: Device, Cooler Master, was not initialized
[ERROR] 21:45:33: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:45:33: Device, SteelSeries, was not initialized
[INFO] 21:45:33: No Wooting devices successfully Initialized!
[INFO] 21:45:33: Device, Wooting, was not initialized
[INFO] 21:45:33: Device, LightFX, was not initialized
[INFO] 21:45:36: Device, Logitech, was shutdown
[INFO] 21:45:38: Retrying Device Initialization
[INFO] 21:45:38: Device, Logitech, was initialized
[ERROR] 21:45:38: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 21:45:38: Device, Corsair, was not initialized
[ERROR] 21:45:38: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 21:45:38: Device, Razer, was not initialized
[ERROR] 21:45:39: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 21:45:39: Device, Roccat, was not initialized
[INFO] 21:45:39: Device, Logitech, was shutdown
[ERROR] 21:45:39: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 21:45:39: Device, Clevo Keyboard, was not initialized
[INFO] 21:45:39: No Cooler Master devices successfully Initialized!
[INFO] 21:45:39: Device, Cooler Master, was not initialized
[ERROR] 21:45:39: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 21:45:39: Device, SteelSeries, was not initialized
[INFO] 21:45:39: No Wooting devices successfully Initialized!
[INFO] 21:45:39: Device, Wooting, was not initialized
[INFO] 21:45:39: Device, LightFX, was not initialized
[INFO] 21:45:49: [IPCServer] Pipe connection established
[INFO] 21:45:58: [IPCServer] Pipe connection lost
[INFO] 21:45:58: [IPCServer] Pipe created 62696216

**Comment by Dagda52** [comment] 2018-10-04 19:56
Happens to me to on corsair devices and on latest cue https://pastebin.com/UJGcit1u

after installing aurorar and disabling (Enable aurora to provide lighting for desktop), after system restart or just closing and opening aurora again, aurora will not work again, until (Enable aurora to provide lighting for desktop) is ticked again.

**Comment by simon-wh** [comment] 2018-10-13 17:39
I've pushed a potential fix for this issue. Can everyone experiencing this please try [this build](https://ci.appveyor.com/project/antonpup/aurora/builds/19486667) and let me know if it helps?

**Comment by LightShaft** [comment] 2018-10-13 17:55
So far it works as intended. I'll keep in touch if I meet any problem

**Comment by Dagda52** [comment] 2018-10-20 06:04
@simon-wh for me, after each restart the keyboard goes completely black, and creates a very large log file, https://www.mediafire.com/file/2ka17slsg14jprt/2018-10-20_01.00.08.log/file

**Comment by DunKalevra** [comment] 2018-10-26 08:10
This build fix it for me. Finished Rise of the Tomb Raider with the Razer Wrapper correctly applied to my K95 RGB Platinum.

**Comment by simon-wh** [comment] 2018-10-29 12:22
@Dagda52 I see, I'll try and have a look into it in a bit and sort that out, seems like it isn't stopping itself from trying to initialize devices. For now, you can try disabling any extra device integrations in Device Manager that you don't actually use which should reduce it a bit.

**Closed** 2019-01-28 22:38 UTC
Labels: bug
