### ISSUE TITLE
Issue with the startup of Aurora

### ISSUE THREAD

**Issue by Taubsiii** [antonpup/Aurora#1873] opened 2020-01-05 16:44 UTC
Expected Behaviour
Aurora should start normally

Actual Behaviour
The left side of the keyboard lights up and Aurora crashes/turns off after about 10 seconds.

Reproduction steps
Just starting it. It is always like this, no matter what I do.

Frequency
Every time

Aurora Version:
0.7.2 and 0.7.1

Previously an Issue?
I had an older version of Aurora working (about 1 year ago) before and I had no issues.

My Software & System
Win10
Logitech G910 and G502
Multiple NZXT and Aurora parts. (which could be the problem I assume)

[2020-01-05 17.37.45.log](https://github.com/antonpup/Aurora/files/4023664/2020-01-05.17.37.45.log)

**Comment by diogotr7** [comment] 2020-01-05 17:25
If you have nzxt hardware it might be the issue yea. Also happens with some asus aura stuff.

**Comment by Taubsiii** [comment] 2020-01-05 17:59
How do I turn it off then?

**Comment by Taubsiii** [comment] 2020-01-09 02:53
Edit: Added info to first post.

**Comment by LufyCZ** [comment] 2020-01-17 17:52
Same problem here. The only supported device I have is a Hue+. Anything I can do to help?

**Comment by diogotr7** [comment] 2020-01-17 22:14
The recent issues seem to be caused by a conflict between aurora and iCue's Aura integration. 
The issues with the nzxt hue+ are known, but we don't know what causes it :/

**Comment by HeasHeartfire** [comment] 2020-01-19 12:34
In my case, I control my corsair keyboard with aurora and my LL fans with icue, since I don't know how to control them in aurora (and I don't have the need tbh).

Since the aura integration in icue, aurora seems to not work but only at startup. I can fix it by disabling and enabling the sdk in icue and then closing aurora if it's open and executing it again, then everything works as expected.

**Comment by finasfinas** [comment] 2020-01-24 12:24
I am experiencing a similar issue, just installed aurora 0.72 on a fresh windows 10 install with the latest logitech and asus aura app.
hardware: logitech G502 hero ( mouse )
                logitech g513 ( keyboard )
                Asus Crosshair VIII impact ( has rgb stuff )
                G.Skill RGB memory 
                enermax liqtech RGB ( cooler connected to mb )

Error on event viewer:

`Application: Aurora.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at AuraServiceLib.IAuraSdk2.Enumerate(UInt32)
   at RGB.NET.Devices.Asus.AsusDeviceProvider.Initialize(RGB.NET.Core.RGBDeviceType, Boolean, Boolean)
   at RGB.NET.Core.RGBSurface.LoadDevices(RGB.NET.Core.IRGBDeviceProvider, RGB.NET.Core.RGBDeviceType, Boolean, Boolean)
   at Aurora.Devices.RGBNet.AbstractRGBNetDevice.Initialize()
   at Aurora.Devices.DeviceManager.Initialize(Boolean)
   at Aurora.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at Aurora.App.Main()

`

`Faulting application name: Aurora.exe, version: 0.7.2.0, time stamp: 0x5de7eca8
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x2600
Faulting application start time: 0x01d5d2af94b39ebc
Faulting application path: C:\Program Files\Aurora\Aurora.exe
Faulting module path: unknown
Report Id: 6dc02e53-72a7-4962-a545-85bb827de4bb
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by HeasHeartfire** [comment] 2020-01-25 16:00
Update: After some testing turns out it was Wallpaper Engine messing with icue at startup. Once I disabled the ICUE plugin everything went back to normal, so mi issue is not related to aurora.

**Comment by diogotr7** [comment] 2020-01-28 14:15
Duplicate of #1895

**Closed by diogotr7** 2020-01-28 14:15 UTC
Labels: Status: Information needed, Type: Bug
