### ISSUE TITLE
Please! I hope for you!

### ISSUE THREAD

**Issue by stannum17** [antonpup/Aurora#962] opened 2018-01-29 19:45 UTC
Hello. I know that I'm only one of hundreds of thousands of customers that use your software, but I want to ask you, even beg you, could you please add support of the HyperX Alloy Elite RGB in the Aurora, I have been using your software before with Logitech G410 and it was amazing experience, but then I bought HyperX keyboard. Thank you so much!!!

**Comment by simon-wh** [comment] 2018-01-29 22:09
Duplicate of #898. There is no sdk available for the keyboard as far as I'm aware so there isn't much I can do to support it.

**Closed by simon-wh** 2018-01-29 22:09 UTC
