### ISSUE TITLE
A layer for the patch overlay of the game

### ISSUE THREAD

**Issue by thu2468** [antonpup/Aurora#633] opened 2017-07-02 10:02 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The patch overlay need a layer of it own so it wont get overlap by another layer added. https://surl.im/i/s6547

### Actual behavior:
It would override the patch overlay of the game

### How often does this problem occur?
Always happen if u add a layer that overlap the LED

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-07-02 12:43
I can't get the image you linked to work and I'm not quite sure exactly what you mean.

**Comment by diogotr7** [comment] 2017-07-02 22:49
I think that he meant the effects the game natively has could be treated as a layer, so we could enable or disable it and change the priority.

**Comment by simon-wh** [comment] 2017-07-02 22:53
Ah, that makes sense. I'll try and add it for the next major version

**Comment by thu2468** [comment] 2017-07-02 23:25
Yeah thats what i mean so something like this. https://surl.im/i/mb9g7 https://surl.im/i/egbbr https://surl.im/i/kauok
So the patch wont get overlap

**Comment by thu2468** [comment] 2017-07-02 23:25
Thank you diogotr ^^

**Comment by simon-wh** [comment] 2017-07-03 01:15
Just noticed that this is a duplicate of #461. Closing...

**Closed by simon-wh** 2017-07-03 01:15 UTC
Labels: enhancement
