### ISSUE TITLE
Overwatch plugin blank keyboard until entering a match

### ISSUE THREAD

**Issue by clytemnestra** [antonpup/Aurora#800] opened 2017-09-19 17:07 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard should change to orange upon entering the game and a match, where it should change its color according to the hero you pick.

### Actual behavior:
Keyboard turns blank, no leds light up upon starting the game. It does light up when entering a game, with the preselected hero's color.

### How often does this problem occur?

This problem occurs every time I start Overwatch

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Have a Corsair K70 LUX RGB or Razer BW Chroma V2 (I tested with both, same behaviour)
2. Install the keyboard software 
3. Apply Overwatch Aurora plugin
4. Start Overwatch
5. Keyboard should turn blank, no LED should light up until you start a game, either QP or practice shooting and a default hero is selected by the game, which will light it up with that hero's color.

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
Just started using it.

### Please include any logs, screenshots, or files that are related to this issue:

This should be the Razer log, from yesterday https://pastebin.com/iyXXyYit
This is the K70 logs from today https://pastebin.com/PLmxw3v3

**Comment by clytemnestra** [comment] 2017-09-19 17:09
Seems to be something from this

```
[ERROR] 9/18/2017 9:07:50 PM: Fatal Exception caught : System.IO.IOException: The process cannot access the file 'D:\Jocuri\Overwatch\RzChromaSDK64.dll' because it is being used by another process.
```

**Comment by simon-wh** [comment] 2017-09-19 17:10
Duplicate of #771

**Closed by simon-wh** 2017-09-19 17:10 UTC

**Comment by clytemnestra** [comment] 2017-09-19 17:32
@simon-wh  Mind telling me how to solve it, please? From looking in that issue I see people are describing blank screen only, but I get colors when joining a match. How can I have any color at the menu? It is pretty annoying to have it blank until joining a game.
