### ISSUE TITLE
Brazilian keyboard layout

### ISSUE THREAD

**Issue by viniciushvc** [antonpup/Aurora#659] opened 2017-07-18 12:58 UTC
Hi there, can i change the layout of Logitech 810, because my keyboard has a key "\" over "ENTER" but aurora is different, and this key don't change the color.

**Comment by brainbug89** [comment] 2017-07-18 13:17
What layout (US, UK, DE, FR, ...) is your keyboard? And which layout you selected at Aurora settings?

**Comment by viniciushvc** [comment] 2017-07-18 13:59
thanks, I did not know that, thanks, I use this keyboard in Brazil with layout US

**Comment by simon-wh** [comment] 2017-08-06 11:31
Duplicate of #504

**Closed by simon-wh** 2017-08-06 11:31 UTC
Labels: enhancement
