### ISSUE TITLE
support for Hyper X Alloy rgb keyboards

### ISSUE THREAD

**Issue by necasary** [antonpup/Aurora#1196] opened 2018-07-28 10:52 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

I'm new to Aurora but very interested in trying it out when the final parts of my rgb setup arrive. 
Only question i have is that the website doesn't show Hyper X keyboards as supported devices so i wanted to ask if i can expect them to be added in future updates or if that is not possible 

kind regards

**Comment by diogotr7** [comment] 2018-07-28 11:16
Unfortunately the hyperx software has no available sdk so support can't be added until they provide one, if they do.

**Comment by simon-wh** [comment] 2018-07-28 11:21
And duplicate of #898/#959

**Closed by simon-wh** 2018-07-28 11:21 UTC
