### ISSUE TITLE
Aurora chewing up more than 70% of memory

### ISSUE THREAD

**Issue by wdellanoce** [antonpup/Aurora#598] opened 2017-06-11 07:47 UTC
### What are you experiencing an issue with?
- [x] Aurora

### What kind of an issue is it?
- [x] Performance problems

### Expected behavior:
Should not use all the resources of the system

### Actual behavior:
Uses most of the ram available on the PC

### How often does this problem occur?
Every time it launches

### Please describe the steps to reproduce this issue:
1. Launch Aurora
2.  Wait
3. 

### What is the version of Aurora you are experiencing this issue with?
beta v0.6.0b

**Comment by simon-wh** [comment] 2017-06-11 19:48
Can you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if the issue is also present in that version?

**Comment by BaltzJ** [comment] 2017-06-11 20:14
I've also experienced this as well I have 28GB of DDR3 Workstation Grade Memory so it isn't that much of a problem it's just that I find Aurora using up the majority of my ram when ever I look in Task Manager (Memory Leak?)

**Comment by simon-wh** [comment] 2017-06-21 17:43
I just left Aurora v0.6.0b running for a while and it didn't increase in memory usage at all, it even went down in memory usage from the start. What settings do you have? Can you try clearing %appdata%/Aurora and see if you still have the same issue? What state is Aurora in when it has this issue?

**Comment by simon-wh** [comment] 2017-07-02 23:19
Possible duplicate of #387. @BaltzJ and @wdellanoce could you try the fix that was posted in that issue and see if it resolves your issues?

**Comment by wdellanoce** [comment] 2017-07-02 23:21
This fixed my issue. I no longer have an issue. Been running fine for quite some time.

**Closed** 2017-07-03 01:07 UTC
Labels: bug, information needed
