### ISSUE TITLE
CM Masterkeys Pro L, numpad 4,5,6 not correct

### ISSUE THREAD

**Issue by Thelgow** [antonpup/Aurora#885] opened 2017-11-27 03:31 UTC
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The Numpad 6 key is not lighting up correctly.
If I assign a color to Num4, nothing happens. If I assign to Num5, then physical 4 lights up. Num6 affects physical num5. It appears they are off alignment by one.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Try any coloring
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Aurora v0.6.1-dev3, I saw changelog said it may be addressed and seems no. 

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-11-28 23:37
Duplicate of #549

**Closed by simon-wh** 2017-11-28 23:37 UTC
