### ISSUE TITLE
[Enhancement] Adding internal PC peripherals support

### ISSUE THREAD

**Issue by Vinny000** [antonpup/Aurora#1089] opened 2018-05-08 14:42 UTC
Could you guys please add integration with Corsair Link or at least ASUS Aura?  I'd like to sync my entire PC including the RGB ram with my keyboard and mouse.

**Comment by simon-wh** [comment] 2018-05-08 15:05
Duplicate of #546

**Closed by simon-wh** 2018-05-08 15:05 UTC
