### ISSUE TITLE
I cant open it.

### ISSUE THREAD

**Issue by emironder** [antonpup/Aurora#626] opened 2017-06-28 20:51 UTC
i've installed aurora but its not working. im opening program and i can see it in task manager but a little later it closes without error. 

windows 10 64 logitech g410
![image](https://user-images.githubusercontent.com/20914294/27659470-41782962-5c5c-11e7-8e55-e2966b0ec241.png)

**Comment by simon-wh** [comment] 2017-06-29 16:33
Can you upload the logs from %appdata%/Aurora/logs and are you running software like MSI Afterburner(It has been known to cause these kinds of issues)?

**Comment by simon-wh** [comment] 2017-07-01 00:55
Duplicate of #605. Please post any follow up in that issue.

**Closed by simon-wh** 2017-07-01 00:55 UTC
Labels: duplicate, information needed
