### ISSUE TITLE
Redragon, sorry for asking it or it is repost but i wanna know

### ISSUE THREAD

**Issue by GalvareyPoco** [antonpup/Aurora#1915] opened 2020-02-19 05:58 UTC
hi, sorry if it is repost or something i wanna know if you can add support for redragon, i saw that it was already requested but i have more information, the keyboard i use and i think all of the redragon ones are using the same hidserv.dll as a lot of manufacturers use like ajazz or gmmk i found a repository that work with my keyboard but on linux, its this one

https://github.com/thanks4opensource/NotLinuxAjazzAK33RGB

bu i saw someone already posted it on #1699 then i saw this post on another site, someone made an api for the ajazz k33 on this site: 

https://linustechtips.com/main/topic/1084018-review-the-ajazz-ak33-40-mechanical-full-rgb-keyboard-doesnt-actually-suck/

is there a way to make it work?
sorry for my bad english

**Comment by diogotr7** [comment] 2020-02-19 15:06
Duplicate of #1699

**Closed by diogotr7** 2020-02-19 15:06 UTC
Labels: Area: Hardware Support, Type: Enhancement
