### ISSUE TITLE
Aurora Wrapper Patch Not Applied. Exception: Could not find a part of path- Logitech

### ISSUE THREAD

**Issue by FTWOblivion** [antonpup/Aurora#1052] opened 2018-04-03 00:27 UTC
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should install Logitech sdk wrapper

### Actual behavior:
says it could find the path C:\programfiles\logitech gaming software etc

### How often does this problem occur?

6.01dev 4
### Does the previous version of Aurora have this issue?
I don't know, it never did this before, i have tried uninstalling reinstalling different versions. no help

### Please include any logs, screenshots, or files that are related to this issue: 
![screenshot 67](https://user-images.githubusercontent.com/26527912/38222697-8cf40a38-36a3-11e8-8aa2-7cbd1bdbd0a3.png)

**Comment by sausje** [comment] 2018-04-03 00:35
For this (and your 2 previous issues), you do have to have the Logitech Gaming Software installed. Which you obviously don't have.

**Comment by FTWOblivion** [comment] 2018-04-03 00:51
Yeah I realized it wasn't giving me that error after installing the lg software. But it wasn't giving me that error before

Sent Via Mobile

________________________________

**Comment by FTWOblivion** [comment] 2018-04-03 01:02
it also still is not working with mirror's edge unfortunately I odn't know what im doing wrong

**Comment by simon-wh** [comment] 2018-05-05 16:28
Duplicate of #752. Assuming it is only Mirror's Edge that is still not working after installing LGS. GTA would be duplicate of #1015

**Closed by simon-wh** 2018-05-05 16:28 UTC
