### ISSUE TITLE
Aurora how to install for n00bs?

### ISSUE THREAD

**Issue by Squallan** [antonpup/Aurora#82] opened 2016-07-24 08:59 UTC
So I've been playing with this for a while, it's an excelent addition for the Keyboard's potential (I got a G910).

But I've been having some issues understanding how to work with some of the features it has... I'm mainly interested in Overwatch and League of Legends, but both requires this "Aurora Wrapper Patch". I have no idea how to apply this patch into the Aurora folder or where to find it.

This is what I've done so far:
-Downloaded the program, tested other games (Rocket League works great)
-Fully customized the Desktop layout (I'm looking forward for the GPU usage color scheme)
-When trying to patch Overwatch, the keyboard goes Black, but even if I actually add the files into the folder that Overwatch is installed, the keyboard does not react to the game as shown in the Demo. This is the reason why I think I'm missing something, I downloaded the "Aurora-Master" folder but I don't know how to apply all that into the program. Am I missing something?
-Same happens with League of Legends, it goes black even if I patch it where it's located, but this asks for a "Wrapper Patch for LightFX", and I don't know where this is or how to add it into Aurora.

-Also, is there any preset for Killing Floor 2, Heroes of the Storm, or some other games beside what is included into Aurora?

Please help, if someone can guide me into this I'll appreciate it a lot... or if there's a video explaining how to do this, please send.

Thank you.

**Comment by RPratt009** [comment] 2016-07-26 04:34
I seem to be having the same issue. something must be happening with the Logitech software overlapping.
If it helps my default location for my game is on my 2nd hard drive with a custom path.

**Comment by Johnnybeefcake** [comment] 2016-07-26 06:33
If you open up Aurora, you can select the directory where your base game is located. For me, it's D:/Battle.net/Overwatch. Yours will probably be in its own folder in C:/Program Files (86) or C:/Program Files (86)/Battle.net . Add the patch to that file through the Aurora program itself. Might be in your system tray if you opened it. Click the Overwatch logo on the left and click "Patch overwatch" > Computer > Select your drive and go from there. 

And no, there are no other games currently supported outside the currently listed games, however if they use lightFX or AlienFX but don't work with your keyboard, open an issue about it and list the game. For example, Robot roller-derby disco dodgeball uses AlienFX but is currently unsupported. Made an issue and Anton said he could get it up in the next patch. I don't think Killing Floor COULD be supported since it's up to the developers to do it, not Anton, but since HotS is a moba, I'd imagine it could be supported. If you need further help, I could try to assist since I have Aurora running on my G910 as well. Trust me, it's what you wanted from your keyboard when you bought it

**Comment by Squallan** [comment] 2016-07-28 03:03
Yeah I did exactly as you just explained, I got Overwatch somewhere else but it shouldn't matter, I noticed it adds a couple of files so the game gives instructions to the Keyboard on how to change according to in-game instructions and numbers. 

The thing is, in both cases, the game seems to communicate with Aurora, because as soon as the game launches, it goes black, like if it is waiting for instructions on what to do, because according to what I've seen, it should change and pop different lighting effects according to the Hero I'm playing and what is happening in-game. (Like for example Hanzo's ulti, it SHOULD show the twin dragon accross the keyboard), but it just stays black, doesn't react to anything I do in-game. The weird thing is, that this only happens with those games that require to patch, because Rocket League works amazing.

I don't think the Overlapping is an issue, I actually think is necesary, because if you close the Logitech Software, Aurora stops working... It uses the software to actually change the color in the hardware.

**Comment by antonpup** [comment] 2016-07-28 03:28
The issues you are expecting with wrappers, is that the wrapper cannot establish a connection with Aurora. Thus it cannot send any lighting data. I am trying to nail this issue down. In the dev build, I have changed Aurora to always run as admin, as well as set security parameters for my inter-process communication. I would like to invite you guys to try this version, and see if it still functions incorrectly.

[Release_razerdebug.zip](https://github.com/antonpup/Aurora/files/387611/Release_razerdebug.zip)

**How to test with razer debug version**
 1. Start this version of Aurora
 2. Patch any Razer game. (For example, Overwatch)
 3. Without closing this version of Aurora, start Overwatch from battle.net and see if lighting works.
 4. Once in main menu, (your keyboard should be orange, but it is possible that it's still black), load into an offline training map (with bots moving around to shoot at). At this point your lighting will either work, or not.

 5. If it does not work, the wrapper should've created a new log file in the game directory called, "output.txt". Please post here contents of "output.txt". It will show me if wrapper has issues communicating with Aurora.


Please note, that the security changes have been applied to all wrappers. But only Razer one has debug logging. So if you had LightFX games not work, try it with this version.

**Comment by AndersAnderson** [comment] 2016-07-31 23:49
I can confirm the exact same issue with League of Legends, unfortunately this lighting doesn't work for me.

I patched the directory and it told me that the patch was successfully installed.
Same with Hotline Miami.

**Comment by Squallan** [comment] 2016-08-02 10:29
Thanks for the reply antonpup

Well, I tried to make it work but whatever I do, it doesn't even want to start up, it changes the colors to what I had set up with the previous Aurora version for like 1 second and then it seems to crash with no error message.

Let me know if you want me to record a quick video of what's happening.

**Comment by antonpup** [comment] 2016-08-02 17:58
Yeah, record a video. If Aurora is crashing, provide Aurora's log at the time of crash as well.

**Closed** 2016-09-18 08:21 UTC
