### ISSUE TITLE
Support keyboard Modecom Volcano Lanparty RGB

### ISSUE THREAD

**Issue by M4teusz6359** [antonpup/Aurora#1875] opened 2020-01-06 17:59 UTC
https://modecom.com/pl/volcano-lanparty-rgb/ <--- Keyboard

https://modecom.com/wp-content/uploads/2017/08/Driver_LanPartyRGB_EN_PL_1.0a.zip <--- Driver

**Comment by xQwexx** [comment] 2020-01-06 21:38
Duplicate of #1442 - No sdk

**Closed** 2020-01-06 23:06 UTC
Labels: Area: Hardware Support, Type: Enhancement
