### ISSUE TITLE
Suggestion: Port ETS2/ATS native Razer support to Aurora

### ISSUE THREAD

**Issue by Sweren** [antonpup/Aurora#1557] opened 2019-05-03 23:23 UTC
SCS Software just released native RGB support for ETS2/ATS but it's only available for Razer Chroma. I suggesto to port the lightning to Aurora.
Thanks

**Comment by simon-wh** [comment] 2019-05-04 10:31
Duplicate of #1556

**Closed by simon-wh** 2019-05-04 10:31 UTC
