### ISSUE TITLE
Support for BF4/BF1

### ISSUE THREAD

**Issue by Oxize** [antonpup/Aurora#198] opened 2016-10-30 15:28 UTC
Any possible support for BF4 and BF1?

**Comment by Pandry** [comment] 2016-10-31 09:57
Possbile it's possible, but it's necvessary to buy the game to see wich are the addresses that aurora should point (if it's not detected as a cheat)...

**Comment by antonpup** [comment] 2016-10-31 14:22
Bf1 is a duplicate, see #130

I don't own BF4, so I can't tell you if it has lighting.

**Comment by Oxize** [comment] 2016-10-31 16:01
Can i check this for you? What do you need for that?

**Comment by antonpup** [comment] 2016-11-01 18:05
Well, you could apply all wrapper patches to the game's folder and see if any lighting effects show up.

**Comment by Oxize** [comment] 2016-11-01 21:01
Where can i find them?

**Comment by antonpup** [comment] 2016-11-01 21:05
Settings -> Devices -> Patch X wrapper.

**Comment by Oxize** [comment] 2016-11-01 21:20
Which one you use for Corsair? The lightfx? The others are for logitech and razer.

**Comment by brainbug89** [comment] 2016-11-01 21:21
You need to use these wrapper for the games not for the keyboard!

**Comment by Oxize** [comment] 2016-11-01 22:17
Okay tried out BF1

When ingame = FULL WHITE Leds
When Dead = Reds Leds
I  saw green also, but dont know where relates too. Happend only 1 time.

So BF1 works with the lights, but its a bit simple with red, white and green.

**Comment by antonpup** [comment] 2016-11-01 22:20
Umm, like I said BF1 is a duplicate of #130 the dev version supports it.

BF4 on the other hand is not tested.

**Comment by Oxize** [comment] 2016-11-01 22:45
Will do that tomorrow. Will let you know.

**Comment by HighKo** [comment] 2016-12-08 11:30
Any progress on this one? I would love to have support for this game.

**Comment by antonpup** [comment] 2016-12-08 15:26
I don't have bf4, but bf1 is already partially working on current public version, and fully works on dev.

**Comment by Kuiriel** [comment] 2016-12-13 20:43
Is there a compiled dev version somewhere available for download and testing? Or a basic guide that I've missed in the forums somewhere on how to compile it with Visual Studio?

I haven't had any luck with the public version of Aurora. I installed the Logitech Wrapper but it made no difference in game (new Corsair Strafe RGB Silent keyboard). My keyboard wasn't recognized by the CUE on the next restart. Another restart later, CUE picked it up. But that could be related to having tested out the Corsair Effects Engine (by Emily Maxwell).

**Comment by brainbug89** [comment] 2016-12-14 00:34
Maybe the Logitech wrapper isn't working. According to https://github.com/antonpup/Aurora/issues/230#issuecomment-265944872 there may be a bug that the Logitech Gaming Software needs to be installed.

**Comment by Kuiriel** [comment] 2016-12-14 04:37
Nice, thank you. I'll give that a shot if I can't get my hands on the dev version to try that first.

**Comment by HighKo** [comment] 2018-02-24 16:09
Working now. Tested with v0.6-dev4.

**Comment by simon-wh** [comment] 2018-09-02 14:58
BF1 support has been added with c8d984714adfa7e52f5597d428b3d449f5eca88c and with some research  it seems BF4 has rgb lighting through lgs which I can try and have a look into as I own bf4.

**Comment by Gurjot95** [comment] 2019-02-03 21:01
Closing for now.

**Closed by Gurjot95** 2019-02-03 21:01 UTC
Labels: game support
