### ISSUE TITLE
The Volume overlay does not work on logitech g910 at aurora dev3

### ISSUE THREAD

**Issue by Luckysneff1988** [antonpup/Aurora#872] opened 2017-11-17 15:02 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
If I change the volume of my soundcard,
I get these over defined keys (F1-F10) shown
### Actual behavior:
Explain here what happened instead.
Nothing happens in the program overview or on my keyboard
### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Aurora Dev 3, set all important settings in Logitech Soiftware
2. I set the keyboard (g910) in Aurora that I use 
3. Change the Volumen  
4. Nothing Happens 

### What is the version of Aurora you are experiencing this issue with?
Aurora v0.6.1 dev3

### Does the previous version of Aurora have this issue?
The previous version, (Aurora v0.6.1 dev2 and all older versions ), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/nVEzr4uv
For screenshots, you can use: 
https://i.imgur.com/LbvAdPK.png

**Comment by simon-wh** [comment] 2017-11-17 19:09
The volume overlay is only triggered using the volume change keys on your keyboard. If you're using that then this is a duplicate of #870

**Closed by simon-wh** 2017-11-17 19:09 UTC
