### ISSUE TITLE
support for ducky shine 6 keyboard

### ISSUE THREAD

**Issue by Milio1985** [antonpup/Aurora#1232] opened 2018-08-24 07:02 UTC
Hello team
I would like to know if the aurora software is compatible with the ducky shine 6 keyboard, or if you plan to add compatibility with this keyboard in the near future.
thanks

**Comment by simon-wh** [comment] 2018-08-25 17:58
Duplicate of #916

**Closed by simon-wh** 2018-08-25 17:58 UTC
