### ISSUE TITLE
Causing lag/high ping in Overwatch

### ISSUE THREAD

**Issue by j14n** [antonpup/Aurora#402] opened 2017-01-21 10:34 UTC
Hi. Not sure whether does it sounds weird but when Aurora is running, I experienced tremendous high ping (1k-2k) in Overwatch and when I exit Aurora, the ping goes back to normal.

**Comment by antonpup** [comment] 2017-01-23 17:11
Duplicate of #359

I don't think Aurora is responsible for lag. If you could confirm with a [previous version v0.5.1d](https://github.com/antonpup/Aurora/releases/tag/v0.5.1d), that it does not cause lag.

**Comment by antonpup** [comment] 2017-01-24 23:17
I just played a game against AI with a team, my ping never went above 20 ms while using 0.6.0b. It's not an issue with Aurora.

**Closed by antonpup** 2017-01-24 23:17 UTC
Labels: duplicate

**Comment by Pandry** [comment] 2017-01-24 23:32
I can confirm, Aurora is not responsible for lag.
Or maybe it is but because MAYBE your CPU can't manage both Overwatch and Aurora, but it would be a hardware problem (you should upgrade your computer)...
