### ISSUE TITLE
Tesoro Gram Spectrum

### ISSUE THREAD

**Issue by ZainHan33** [antonpup/Aurora#1846] opened 2019-12-15 21:24 UTC
Hi

I found this

https://github.com/antonpup/Aurora/issues/1564

But have not been able to figure out how to make it work. I looked through the pull requests for adding a new device but that did not help. Ive got all the redistributables and .net framework installed. 

Thanks

**Comment by diogotr7** [comment] 2020-04-05 14:36
Duplicate of #1564

**Closed by diogotr7** 2020-04-05 14:36 UTC
Labels: Area: Hardware Support, Type: Enhancement
