### ISSUE TITLE
cant use Razer synapse->philips HUE and Aurora simultaneously for overwatch

### ISSUE THREAD

**Issue by Thinktank1803** [antonpup/Aurora#980] opened 2018-02-14 04:51 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (razer)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
aurora does its overwatch thing AND razer does its overwatch thing through the philips hue light strips

### Actual behavior:
i can make aurora do its thing (beautifully i might add, well done) if i keep the patched in files present in the overwatch folder, OR i can make razer do its thing to the philips hue led strips if i delete the patch files thus making aurora cease to function

### How often does this problem occur?
every time. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. run aurora and razer synapse (the new version with philips hue integration)
2. launch overwatch while the aurora patch files are in place
3. note that aurora controlled devices (keyboard, mouse, mousepad) do the correct colors
4. launch overwatch without the aurora patch files
5. note how razer synapse recognizes overwatch and does its thing.

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
it probably would, yes.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

i dont want to buy $300 of razer stuff to be able to synchronize more lights with overwatch. beyond that, atmo-orb seems more intimidating and specialized than the simple philips hue light kits. at this point i have a bunch of corsair stuff that i really like and i really appreciate that your program makes them work with overwatch. but i also have this philips hue stuff that i got because razer, for all their faults, can make it do fun things and philips in general integrates their lighting well with everyone. 

if by some miracle you could add philips hue integration to aurora that would be beautiful and i would be delighted (in progress i believe, im in no rush). otherwise unless i misunderstand how aurora gets its overwatch data, it seems like aurora functions as a very "its me or them" authority on lighting.

please let me know if you want to know more about this issue and thanks again everyone for making this lovely program, its been a delight to use.

**Comment by simon-wh** [comment] 2018-02-14 13:03
Philips HUE has an API available that I can support once I've reworked the device layout system to properly support devices outside of keyboards & mice. Also, duplicate of #358

**Closed by simon-wh** 2018-02-14 13:03 UTC
