### ISSUE TITLE
0.6.1 Beta - Num 6 not lighting

### ISSUE THREAD

**Issue by jackdowsonuk** [antonpup/Aurora#899] opened 2017-12-05 12:42 UTC
The new beta release seems to have really solved many issues, including one where the Enter key didn't light up. Now this all works perfectly, however there is one issue...

The numpad light for the number 6 isn't lighting at all. This is on a default install of the beta version.

I am using the UK layout for the Cooler Master Masterkeys Pro L. This issue is happening everywhere within Windows. I have even tried setting specific layers for that key, however it isn't making any difference at all.

I am using three lock colour layers (for caps, num and scroll), and a solid colour layer for the rest of the keys.

NOTE: It appears that when selecting Num 6 to light on its own within its own layer, it lights Num 5 instead.

### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Num 6 key should be lit

### Actual behavior:
Num 6 key is not lit

### How often does this problem occur?

This problem occurs all of the time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

- This can be reproduced simply by opening the software and setting the key to light.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1 Beta

### Does the previous version of Aurora have this issue?
The previous version did not have this issue, however had other issues with other keys not lighting up (for example, Enter).

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Thelgow** [comment] 2017-12-07 13:40
Its a known issue apparently. I reported similar a week ago, https://github.com/antonpup/Aurora/issues/885  
From what I saw settings to Num4 do nothing, setting to Num5 actually affect Num4, and settings for 6 affect 5. So it looks like its shifted over by one.

**Comment by simon-wh** [comment] 2017-12-08 17:51
Duplicate of #549 and #747

**Closed by simon-wh** 2017-12-08 17:51 UTC
