### ISSUE TITLE
GTA 5 light layers not working

### ISSUE THREAD

**Issue by SahilRS200** [antonpup/Aurora#1304] opened 2018-10-22 22:29 UTC
### Expected behavior:
GTA 5 layers should work as expected

### Actual behavior:
The layers do not update as per game state

### How often does this problem occur?

This problem occurs when i try to launch gta 5. CS Go light works fine. But GTA 5 lighting is stuck at the last preview that was done. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Enable GTA 5 layers in Project Aurora
2. Launch GTA 5
3. Load story mode and expect character specific lighting

### What is the version of Aurora you are experiencing this issue with?

beta v0.6.3

### Does the previous version of Aurora have this issue?
This the only version i have used

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/Gqg1RJnS
https://pastebin.com/TqzTQrjv
[2018-10-23 03.27.30.log](https://github.com/antonpup/Aurora/files/2503619/2018-10-23.03.27.30.log)
[2018-10-23 03.54.00.log](https://github.com/antonpup/Aurora/files/2503620/2018-10-23.03.54.00.log)

**Comment by simon-wh** [comment] 2018-10-23 12:56
Duplicate of #1015

**Closed by simon-wh** 2018-10-23 12:56 UTC
