### ISSUE TITLE
Bunch of crashes

### ISSUE THREAD

**Issue by Blakcbird** [antonpup/Aurora#1129] opened 2018-06-10 01:04 UTC
So, after about 2 hours, this appears
https://cdn.discordapp.com/attachments/316643315741097986/455175227010449438/unknown.png
I don't know why, or how to fix this

**Comment by simon-wh** [comment] 2018-06-11 14:28
Could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-325/artifacts) and see if you still experience the issue? I believe the issue has already been fixed in the dev branch.

**Comment by Blakcbird** [comment] 2018-06-11 20:32
Yep, it's worked perfectly so far, but I have another question, I'm using a laptop, which has an RGB keyboard on it, by Steelseries, and tthe keyboard I'm using externally is also by Steelseries, so when I enable Aurora in SSE3m it overrides the settings I have for my laptop's keyboard, I'd like to know if there is any way for me to be able to change that, because I just want my keyboard on my laptop to be red and not have 3 different colorsMaybe an update in Aurora to set multiple keyboards?The laptop's keyboard is the ''MSI 3 Zone RGB Keyboard'', I'm using an MSI GT62VR Dominator Pro if that helpsThanks for this working build, and good luck improving this app
Also, think you could add support for the G403?
And, maybe a huge stretch, but look into the Trust GXT Glide to see if you are able to control the LEDs from software instead of only hardware?    On Monday, June 11, 2018, 4:28:42 PM GMT+2, Simon W <notifications@github.com> wrote:  
 
 
Could you try this build and see if you still experience the issue? I believe the issue has already been fixed in the dev branch.

**Comment by simon-wh** [comment] 2018-06-12 10:17
@Blakcbird I just noticed that you also created the other issue I just replied to, does that mean you're no longer having issues with Aurora interacting with SSE3? Also, multiple keyboards is not something that is going to be possible with v0.6.* (as per #1126) It will potentially be possible for you to do it with v0.7.0, once that is done, however, it may not be possible to control multiple keyboards independently through SSE3 (I haven't checked though). The G403 should work by selecting a mouse with a similar layout. Without access to the Trust GXT Glide there is no chance as there is no publicly available sdk to interact with the device that I can find (and it's unlikely to be possible considering they don't seem to even have their own software to control it.)

**Comment by 3276908917** [comment] 2018-07-15 05:37
I've tried both the build that you linked here and the latest bleeding-edge build but I am still getting the same crashes (though I get one prompt, not several). Aurora usually crashes around 15 minutes after starting. Technically my lighting profile continues to function until I respond to the crash window, but I would still like to fix this because the prompt periodically requests focus, minimizing whatever game I'm playing.
![aurora_crash](https://user-images.githubusercontent.com/12931948/42730859-980354f2-87b5-11e8-93c1-e68dc3038485.png)

**Comment by 3276908917** [comment] 2018-07-18 23:59
0.6.1-dev4-373 currently, although I believe I also tried 0.6.1-dev4-325 and regular 0.6.1-dev4

**Comment by grimid** [comment] 2018-07-19 02:24
Using build 325 hasn't fixed it for me either. Issue persists.

**Comment by simon-wh** [comment] 2018-07-19 09:07
@grimid build 325 is pretty old, if you're going to use those builds you should probably use the latest.

@3275908917 The builds with random characters at the end are from pull requests, so you probably want to avoid them, you should stick to the ones just ending in a number

**Comment by simon-wh** [comment] 2018-07-31 19:05
The background worker crash has been confirmed to be fixed in the dev branch by someone who was repeatedly experiencing it, it'll be in the v0.6.2b release

**Closed by simon-wh** 2018-07-31 19:05 UTC
Labels: bug, feedback needed
