### ISSUE TITLE
Support for Star Citzen

### ISSUE THREAD

**Issue by r4ptus** [antonpup/Aurora#384] opened 2017-01-16 15:23 UTC
Are u planning to support Star Citizen in the near future?
so that the colors are changing if u sit in a spaccraft or when u are on ur feet?

**Comment by JoniSykes** [comment] 2017-01-17 16:00
@r4ptus This isn't really an issue, but a feature request.
Perhaps @antonpup Can provide a better way of request features to avoid issues getting spammed?

**Comment by antonpup** [comment] 2017-01-17 17:45
Duplicate of #190

**Closed by antonpup** 2017-01-17 17:45 UTC
