### ISSUE TITLE
Support for Swiss German layout please

### ISSUE THREAD

**Issue by Wakers** [antonpup/Aurora#628] opened 2017-06-29 16:08 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [x] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Under automatic language selection, the £ and < keys should be illuminated, they are not. When selecting German layout, which should be the same, they are not illuminated, and the z and y illumination is wrong (illuminated as if the layout is QWERTY, which is wrong for DE, which should be QWERTZ)

The Enter key should also be illuminated, sometimes it is not.

### How often does this problem occur?
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

Assigning a lighting colours to the £,> and Enter key.

### What is the version of Aurora you are experiencing this issue with?
0.6b

### Does the previous version of Aurora have this issue?
I don't know.

### Please include any logs, screenshots, or files that are related to this issue:
Here's a link to the Swiss German and German layouts for reference:

https://en.wikipedia.org/wiki/File:KB_Swiss.svg

https://en.wikipedia.org/wiki/File:KB_Germany.svg

**Comment by brainbug89** [comment] 2017-07-02 14:25
QWERTZ (DE layout) works fine for me.

**Comment by simon-wh** [comment] 2017-07-02 23:17
Duplicate of #463. Closing...

**Closed by simon-wh** 2017-07-02 23:17 UTC
Labels: bug
