### ISSUE TITLE
Aurora CONSTANTLY using internet bandwidth to upload 24kps. To where? Why?

### ISSUE THREAD

**Issue by Jesusjones1024** [antonpup/Aurora#985] opened 2018-02-18 10:38 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Using internet bandwidth to upload in background constantly. Turned off all update settings, but even then should only be downloading. 24kps is a lot of bandwidth...

### Expected behavior:
Explain here what should happen.

Not use internet.

### Actual behavior:
Explain here what happened instead.

Constantly sends 24kps

### How often does this problem occur?

This problem occurs... (Fill in here)

Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open app
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

Newest

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

New user

### Please include any logs, screenshots, or files that
![aurora using internet]
![aurora using internet](https://user-images.githubusercontent.com/36593239/36350889-046587f2-1455-11e8-8e22-45d41d8376f3.jpg)

 are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

https://imgur.com/xDzHftP

**Comment by simon-wh** [comment] 2018-02-18 15:43
It is most likely caused by AtmoOrb, see #342. The issue with it has been fixed in the dev releases, please either disable AtmoOrb or update to one of the dev releases.

**Closed by simon-wh** 2018-02-18 15:43 UTC
