### ISSUE TITLE
Add discord overlay or Fix To LED Pause

### ISSUE THREAD

**Issue by thu2468** [antonpup/Aurora#632] opened 2017-07-02 03:39 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Have a discord overlay like skype overlay. Would like to have something simular to the logictech applet or something better. https://surl.im/i/sper6

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by thu2468** [comment] 2017-07-02 03:47
Or a fix so u can use discord applet at the same time as the aurora. Because what happen is when there a update to the discord applet onto the LED. It pauses Aurora LED and doesnt switch color

**Comment by simon-wh** [comment] 2017-07-02 10:31
Duplicate of #297

**Closed by simon-wh** 2017-07-02 10:31 UTC
Labels: duplicate
