### ISSUE TITLE
Rocket League only background

### ISSUE THREAD

**Issue by Poolitzer** [antonpup/Aurora#821] opened 2017-10-01 10:36 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Rocket League)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
I think, 
-   Team-based background lighting
-     Score-split for background effect
-     Boost indicator

### Actual behavior:
Explain here what happened instead.
Only the blue background
### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora
2. Start Rocket League
3. Look at the keyboard

### What is the version of Aurora you are experiencing this issue with?

My version is... v.0.6.0b

### Does the previous version of Aurora have this issue?
I guess ;P

**Comment by simon-wh** [comment] 2017-10-01 17:48
Duplicate of #185

**Closed by simon-wh** 2017-10-01 17:48 UTC
