### ISSUE TITLE
Can't get Overwatch to show any lights. 

### ISSUE THREAD

**Issue by MightyJoeTYoung** [antonpup/Aurora#643] opened 2017-07-06 22:46 UTC
What are you experiencing an issue with?

- [x ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [x ] Aurora Wrapper
- [x] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [Can't get any lights to show up for Overwatch on my Logitech G810 ] Other, (Fill in another type of issue here)

### Expected behavior:
My keyboard should behave like the Razr Blackwidow, when selecting a character, my keyboard responds to each one.

### Actual behavior:
When I launch Overwatch, all the lights on my keyboard shut off

### How often does this problem occur?
Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Installing Aurora
2. Patching the Overwatch file
3. Opening Overwatch and the lights will shut off.

### What is the version of Aurora you are experiencing this issue with?
The latest, just downloaded it.

### Does the previous version of Aurora have this issue?
Don't know.

**Comment by simon-wh** [comment] 2017-07-07 10:09
Duplicate of #589. Try the fix mentioned in that issue or try the [latest development release](https://github.com/antonpup/Aurora/releases) if you're still having issues.

**Closed by simon-wh** 2017-07-07 10:09 UTC
