### ISSUE TITLE
Ajazz AK-33 keyboard support?

### ISSUE THREAD

**Issue by StarrHD** [antonpup/Aurora#847] opened 2017-10-30 19:04 UTC
- [x] Aurora Wrapper
- [x] Aurora supported device, (Ajazz AK33 RGB)
- [x] Other, (no device support)

**Comment by diogotr7** [comment] 2017-10-30 19:08
That keyboard has been discussed before here and as far as i know it doesn't have an sdk, so there is not much that can be done to support it.

**Comment by StarrHD** [comment] 2017-10-30 19:12
do you mean this? (http://a-jazz.com.cn/download_en.aspx)

**Comment by simon-wh** [comment] 2017-10-30 20:31
Duplicate of #756, #583, #505. Please use the search function before opening an issue.

**Closed by simon-wh** 2017-10-30 20:31 UTC
