### ISSUE TITLE
RocketLeague integration does not work!

### ISSUE THREAD

**Issue by ChaosgamesTV** [antonpup/Aurora#765] opened 2017-08-27 07:49 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [x] Aurora supported game, (RocketLeague)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (integration does not work)

### Expected behavior:
The Rocket League Integration does not work! I read in the software that i can contact you if that happens.

### Actual behavior:
The Rocket League Integration does not work! I read in the software that i can contact you if that happens.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Rocket League
2. Effects does not work
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta 0.6.0b)

### Does the previous version of Aurora have this issue?
I dont know i have the game since 3 days.

**Comment by simon-wh** [comment] 2017-08-27 13:47
Duplicate of #185

**Closed by simon-wh** 2017-08-27 13:47 UTC
