### ISSUE TITLE
Anyone who could help me out on setting up the rgb effects for The Division on G810?

### ISSUE THREAD

**Issue by jargonh** [antonpup/Aurora#471] opened 2017-03-01 20:35 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (The Division)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (no RGB light at all)

### Expected behavior:
Keyboard should be lit and effects would be there when ammo or life is low.

### Actual behavior:
Just plain dark, no leds lid at all.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Uplay
2. Start The Division
3. Game is playable but no RGB

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0.b)

### Does the previous version of Aurora have this issue?
Didn't ran previous versions of Aurora.
[2017_01_03log.txt](https://github.com/antonpup/Aurora/files/811961/2017_01_03log.txt)

**Comment by anzabanza** [comment] 2017-03-02 17:57
You have to turn on the option in settings

**Comment by jargonh** [comment] 2017-03-02 19:10
In the game I've put the selector to use the 3th party logitech keyboard effects. (it worked before I used Aurora).

**Comment by anzabanza** [comment] 2017-03-03 17:38
I'm not sure what could be wrong then. I always worked for me. Which keyboard are you using?

**Comment by anzabanza** [comment] 2017-03-03 17:41
There seems to be an error getting the game state (which leds it should turn on) from the game. Try reinstalling aurora, trying an older version or repatching the sdk.

**Comment by jargonh** [comment] 2017-03-05 17:50
Okay, did some testing today.
Using a previous version (aurora folder without installer), all profiles seem to work perfect.
As soon as I update to the latest version (auroraupdater), The Division doesn't work anymore.

Also, but that is rather a minor issue, the profile i made for my desktop is selectable in the older versions of Aurora but the profile doesn't seem to load.

So 2 options:
- using an older version of Aurora and not updating to the newer version.
- using the newer version and quit Aurora and use Logitech's software instead for playing The Division.

**Comment by anzabanza** [comment] 2017-03-06 14:25
I haven't played the division with the newest version of aurora so I can't confirm anything. If all other profiles are working as you said (Particularly the games that have peripheral lighting support like overwatch)  , then the problem is with aurora not "translating" the data from one sdk to another or not properly receiving the data outputted by the sdk. I might be wrong as I don't really know much about C languages and only had a quick peek at the aurora source code. Otherwise I don't really see a problem with the older version of aurora as it offers basically the same features as the new one.

**Comment by anzabanza** [comment] 2017-03-06 14:30
About the profile, I use the standard ones in aurora, but there might be a bug with aurora reading the profiles (from current and previous versions of it). Try creating one in the new version or the profiles from old versions might not work at all because antonpup changed the way the effects are applied (it uses layers now instead of color zones)

**Comment by antonpup** [comment] 2017-03-06 21:09
The Division integration is broken on the current public version, like mentioned before here: #416 and #382

I believe it is already fixed on dev branch. But I will still be updating the wrappers with g-keys and what not.

**Comment by jargonh** [comment] 2017-03-07 09:29
Okay, so I just be patience and I'll see it when it's implemented.
Thanks

**Closed** 2017-07-02 23:13 UTC
Labels: bug
