### ISSUE TITLE
Import Razer Chroma profiles

### ISSUE THREAD

**Issue by computerboy0555** [antonpup/Aurora#565] opened 2017-05-16 18:26 UTC
Is there anyway to enter those files into aurora? if there isn't could u enter this feature please? Tnx
[https://s3.amazonaws.com/razer-assets/downloads/chroma/profiles/keyboards/blackwidow/Poicenz/Poicenz_heart%20shape.razerchroma](url)

**Comment by simon-wh** [comment] 2017-06-01 01:45
Duplicate of #429

**Closed by simon-wh** 2017-06-01 01:45 UTC
Labels: enhancement
