### ISSUE TITLE
Rainbow Six Siege Support

### ISSUE THREAD

**Issue by DeeHechEss** [antonpup/Aurora#600] opened 2017-06-12 09:17 UTC
Rainbow six siege support would be great, some of the effects that could be done would be:
- Team Color
- Health Meter
- Ammo Left
- Blood Effects
- Flash Grenades
- Grenades/C4 Effect

**Comment by simon-wh** [comment] 2017-06-12 13:38
Duplicate of #349

**Closed by simon-wh** 2017-06-12 13:38 UTC
