### ISSUE TITLE
Not launching on startup

### ISSUE THREAD

**Issue by jdubnz** [antonpup/Aurora#452] opened 2017-02-15 05:19 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Aurora is not launching on windows startup)

### Expected behavior:
Explain here what should happen.
Aurora to launch on startup
### Actual behavior:
Explain here what happened instead.
It does not launch. Has to be done manually.
### How often does this problem occur?

This problem occurs... (Every time)

Skype overlay is disabled (this fixed the issue a long time ago) and Aurora runs as admin.
Potentially launches before LGS? => not detecting any devices and ends process? But I think Aurora scans for devices for a while incase that happens...

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
My devices are Logitech g502 mouse and G810 Orion keyboard.

1. Turn on computer
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
I am unsure sorry, has been an issue for a while now.

### Please include any logs, screenshots, or files that are related to this issue:
PasteBin link to most recent Log file.
http://pastebin.com/Q3QjPBvU

**Comment by antonpup** [comment] 2017-02-16 03:14
Thank you for reporting this.

I believe the issue is related to how I handle the log file. I will be changing that, so hopefully, it won't fill people's memory.

What you should try is, run Aurora as administrator, and see if that produces the same issue after a few days. If it doesn't, then my fix should work. If it does, we will investigate further.

**Comment by antonpup** [comment] 2017-02-16 03:15
I believe Aurora doesn't start due to permission conflicts. I'll look into it.

**Comment by vinochino** [comment] 2017-02-20 16:19
Hey, got the same autostart issue. Maybe it helps if I post my latest log too: http://pastebin.com/b8x9KN1B

**Comment by babooka37** [comment] 2017-02-22 21:24
I have the same problem with the latest version. I mentioned that it happens if I set in aurora "Run as administrator". Without it loads up fine.
Without administrator rights it doesn't hold a profile for aces.exe x64 (War Thunder game). It launch a profile with the game, but if I minimize it switch back to default and would not come back when I'm back in the game again.

**Comment by antonpup** [comment] 2017-02-22 21:33
@babooka37 The issue you described is due to permissions issues. I.e. A non-admin process cannot look at admin process. So, the solution to your issue is to always run Aurora as admin.

**Comment by babooka37** [comment] 2017-02-22 21:38
I understand, but the problem with admin permission is that aurora will not autostart.

**Comment by antonpup** [comment] 2017-02-22 22:14
@babooka37  Good point. Will look into.

**Comment by brainbug89** [comment] 2017-02-23 21:22
> I understand, but the problem with admin permission is that aurora will not autostart.

I also noticed this problem. I need to run Aurora with admin permission, but then it won't autostart. :-/

**Comment by simon-wh** [comment] 2017-07-06 09:52
This should be fixed with the changes I've made to startup. It now uses the Task Scheduler so that it can launch on boot as admin and now is set to require admin in the app manifest. These changes will be available in 0.6.1 or the next pre-release.

**Comment by simon-wh** [comment] 2017-07-30 04:06
You can get the changes in the [latest prerelease](https://github.com/antonpup/Aurora/releases). I'm going to close this issue because I'm definitely going to forget about it when it comes to the release of 0.6.1

**Closed by simon-wh** 2017-07-30 04:06 UTC
Labels: bug
