### ISSUE TITLE
Can you Support the Corsair RGB mousepad?

### ISSUE THREAD

**Issue by ChaosgamesTV** [antonpup/Aurora#810] opened 2017-09-27 21:10 UTC
Hello i want to ask you if you can support the corsair RGB mousepad i have one of them and it works when i say aurora that it is a mouse but then my logitech mouse does not work!
It would be very nice if you can fix this problem. It would be also very nice if you can support every zone on the pad;). Maybe you can make a option to run 2 mouses the same time that would be a very nice start.

Greetings from Germany 
Henrik Fährmann

**Comment by simon-wh** [comment] 2017-09-27 22:31
Duplicate of #481

**Closed by simon-wh** 2017-09-27 22:31 UTC
