### ISSUE TITLE
Aurora will not start

### ISSUE THREAD

**Issue by Mehammers** [antonpup/Aurora#1922] opened 2020-02-28 19:18 UTC
### Expected Behaviour
the program will start

### Actual Behaviour
when i start the program i see it start in the task manager, but after a few seconds it gets shutdown

### Frequency
this happends every time i start the program

### Aurora Version:
v0.7.2

### Previously an Issue?
i dont think so, it did work some time ago, but it has not worked for a long time

**Comment by diogotr7** [comment] 2020-02-28 22:38
Do you have asus aura?

**Comment by Mehammers** [comment] 2020-02-28 23:03
yes

**Comment by diogotr7** [comment] 2020-02-28 23:10
Duplicate of #1895

**Closed by diogotr7** 2020-02-28 23:10 UTC
Labels: Type: Bug
