### ISSUE TITLE
Support for more mouse leds (razer mamba)

### ISSUE THREAD

**Issue by GugZi** [antonpup/Aurora#1310] opened 2018-10-26 11:14 UTC
Why can't i see any razer mouse?
![unavngivet](https://user-images.githubusercontent.com/4528562/47563126-04a6f980-d921-11e8-8150-63d0abaac1ab.png)

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.3

**Comment by diogotr7** [comment] 2018-10-26 13:58
If you choose a similar one it should work.

**Comment by GugZi** [comment] 2018-10-27 03:05
But i have a razer mouse not another one? So how can it work?

**Comment by GugZi** [comment] 2018-10-27 13:17
But then i can't set the color i want to my mouse. cuz it not that mouse image.
![udklip1](https://user-images.githubusercontent.com/4528562/47604532-73588580-d9fb-11e8-9565-ee5d8f837b67.PNG)

**Comment by axe-murderer** [comment] 2018-10-27 17:19
it's just the image that changes. your mouse will still change colors if you set it.

**Comment by GugZi** [comment] 2018-10-27 17:50
But i still can’t change the color on my mouse like i want to have it cuz there is not a mouse like the one i have.. in the description is my mouse as supported so i don’t get it

**Comment by axe-murderer** [comment] 2018-10-27 17:52
did you follow the first-time instructions for razer and looked in aurora's device manager to make sure that your mouse is detected?

**Comment by GugZi** [comment] 2018-10-27 17:53
Yup, my keyboard is working fine also razer

**Comment by axe-murderer** [comment] 2018-10-27 17:54
hmm, it shows in aurora's device manager? what happens when you try to actually set a color?

**Comment by diogotr7** [comment] 2018-10-27 18:00
@GugZi what's your mouse? also if you don't mind having this conversation in discord would be better to not spam notifications :) https://discord.gg/YAuBmg9

**Comment by simon-wh** [comment] 2019-01-21 15:38
Duplicate of #119

**Closed by simon-wh** 2019-01-21 15:38 UTC
