### ISSUE TITLE
Rocket League no effects

### ISSUE THREAD

**Issue by nben** [antonpup/Aurora#961] opened 2018-01-29 19:10 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, Rocket League
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, no effects

### Expected behavior:
Keyboard should change colours e.g. depending on amount of boost.

### Actual behavior:
Keyboard maintains background colour.

### How often does this problem occur?
Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Aurora
2. Choose keyboard
3. Launch Rocket League

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1-dev4

### Does the previous version of Aurora have this issue?
Previous version probably worked with previous Rocket League update - unless I'm not experiencing an issue due to changed memory addresses.

**Comment by simon-wh** [comment] 2018-01-29 22:08
Duplicate of #185

**Closed by simon-wh** 2018-01-29 22:08 UTC
