### ISSUE TITLE
Masterkey Pro L RGB 

### ISSUE THREAD

**Issue by bobtb98** [antonpup/Aurora#680] opened 2017-07-23 09:06 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Whole keyboard should light up

### Actual behavior:
Numpad 4, Pause Key, and the P1-P4 not lighting up 

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Overwatch and aurora
2.  almost every key light up except those few key that are being stated at the top
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.60)

### Does the previous version of Aurora have this issue?
Not applicable

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-07-23 14:03
Duplicate of #549

**Closed by simon-wh** 2017-07-23 14:03 UTC
