### ISSUE TITLE
Support for fans

### ISSUE THREAD

**Issue by rogorman9** [antonpup/Aurora#1240] opened 2018-09-01 02:07 UTC
Are there any plans to support RGB fans? I have Corsair fans and a Corsair keyboard, so with Aurora open the fans won't light up since iCUE sees them as being controlled through the SDK by another program (Aurora). I have a mouse too, so this would require adding more device slots.

**Comment by simon-wh** [comment] 2018-09-02 14:25
Duplicate of #1055

**Closed by simon-wh** 2018-09-02 14:25 UTC

**Comment by Gurjot95** [comment] 2019-01-31 18:01
Try
#1421
