### ISSUE TITLE
Aurora not initializing Asus properly after chipset update

### ISSUE THREAD

**Issue by KalyneTV** [antonpup/Aurora#1867] opened 2020-01-04 03:25 UTC
### Expected Behaviour
The program should initialize and manage RGB on the ASUS motherboard.

### Actual Behaviour
Aurora hangs forever while initializing Asus.

### Reproduction steps
The chipset used was version 1.7.29.0115 for the Crosshair VI Hero (WI-FI AC) for an AMD Ryzen 7 1800x, on Windows 10 x64.

The issue happens when initializing Asus somewhere within [this loop](https://github.com/antonpup/Aurora/blob/e96548b1d37f612a7b0404c5f7a7cd3b208d89e7/Project-Aurora/Project-Aurora/Devices/DeviceManager.cs#L216)

I added a log message that runs for each device at the start of the loop. On the Asus device it starts and never loops again.

Adding the following to `devices_disabled` in the config file allows Aurora to start successfully:

```
"Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
```

### Frequency
Every time.

### Aurora Version:
0.71, 0.7.2 stable and 0.7.2+781 bleeding.

### Previously an Issue?
Not before updating the chipset driver.

**Comment by diogotr7** [comment] 2020-01-14 14:33
Could Asus Aura also have updated in the meantime? The asus support in Aurora is known ro be problematic as asus's sdk isnt the easiest to work with and has a lot of issues :(

**Comment by diogotr7** [comment] 2020-01-17 22:19
After some investigation, I think this issue might be caused by Corsair and Asus's recent collaboration in integrating asus aura motherboards into iCue. Did you install this plugin?

**Comment by KalyneTV** [comment] 2020-01-18 09:11
Apologies for the slow response. Yes, I did install iCUE at the time, however, I also tried afterwards without having the plugin installed since iCUE seemed to be freezing and not properly working.

**Comment by diogotr7** [comment] 2020-01-28 14:16
I assume this is a duplicate of #1895, so please let's keep all relevant info there.

**Closed by diogotr7** 2020-01-28 14:16 UTC
Labels: Brand: Asus, Status: Information needed, Type: Bug
