### ISSUE TITLE
Ducky Response Lag When Not Debugging

### ISSUE THREAD

**Issue by umbreon222** [antonpup/Aurora#2086] opened 2020-06-10 21:56 UTC
### Expected Behaviour
~30ms device response time

### Actual Behaviour
~154ms device response time

### Reproduction steps
When debugging Aurora, I get around a 30ms device response time and no visual lag. When I run Aurora without debugging, I get around a 144ms device response time with a lot of visual lag. This only affects the keyboard, both my mouse (Logitech G703) and the bitmap preview have no visual lag.

![Screenshot (1)](https://user-images.githubusercontent.com/8075185/84322729-14e20b80-ab3b-11ea-8fe5-23a0eb3ffbed.png)
![Screenshot (3)](https://user-images.githubusercontent.com/8075185/84322803-3c38d880-ab3b-11ea-933e-4fb30cde07d2.png)

### Frequency
This happens every time I launch Aurora.

### Aurora Version:
I'm using the current code base (Beta v0.8.0).

### Previously an Issue?

This issue is prevalent in all past versions since the Ducky keyboard support has been added.

**Comment by thedmd** [comment] 2020-08-03 07:37
Still here in v0.8.1

**Comment by Rukario** [comment] 2020-09-11 15:05
Hope to see it fixed soon, just got Ducky One2 TKL board today and I can see the animation lags too much compared to Logitech G910.

**Comment by craftycorvid** [comment] 2020-11-16 20:35
Still seeing this issue on my Ducky One2 on the latest bleeding edge build.

**Comment by tibernero** [comment] 2020-12-30 22:12
Just chiming in to say that I'm having response lag issues as well, pretty much identical to Umbreon's issue.

Running v0.8.1 on the Ducky Shine 7.

**Comment by umbreon222** [comment] 2020-12-31 01:54
I'm currently playing around with this issue and I think I have a fix. I'm not certain why the code which is causing this was added so I want to take some time to test out my fix over the course of a week or so. I just want to be certain I didn't break anything or cause instability. If you're curious or want to test out my fix I made a branch called "umbreon222:bugfix/ducky_response_lag_2".

Edit: I based my first branch off master instead of dev so I updated my comment with the new branch name

**Comment by tibernero** [comment] 2020-12-31 02:15
Thanks so much for letting me know! I would love to give it a try.

Are there instructions I can find on how to install the branch?

**Comment by umbreon222** [comment] 2020-12-31 03:58
> 
> 
> Thanks so much for letting me know! I would love to give it a try.
> 
> Are there instructions I can find on how to install the branch?

Unfortunately, you'd have to build the branch and run it manually using visual studio.

**Comment by tibernero** [comment] 2020-12-31 15:26
> 
> 
> > Thanks so much for letting me know! I would love to give it a try.
> > Are there instructions I can find on how to install the branch?
> 
> Unfortunately, you'd have to build the branch and run it manually using visual studio.

Tried building it in VS but it seems there is a solution missing that doesn't allow me to build the project, called "SBAuroraReactive.vcxproj"

I think I'll just wait for you guys to hopefully integrate this into the application itself. But I'm looking forward to it!

**Comment by umbreon222** [comment] 2020-12-31 15:43
> 
> 
> > > Thanks so much for letting me know! I would love to give it a try.
> > > Are there instructions I can find on how to install the branch?
> > 
> > 
> > Unfortunately, you'd have to build the branch and run it manually using visual studio.
> 
> Tried building it in VS but it seems there is a solution missing that doesn't allow me to build the project, called "SBAuroraReactive.vcxproj"
> 
> I think I'll just wait for you guys to hopefully integrate this into the application itself. But I'm looking forward to it!

Oh, you probably forgot to pull the submodules. Running `git submodule update --init --recursive` would solve your issue.

As an update, I had aurora running with my changes all night and so far so good. I'll probably create the PR either today or tomorrow.

**Comment by tibernero** [comment] 2020-12-31 16:56
> 
> 
> > > > Thanks so much for letting me know! I would love to give it a try.
> > > > Are there instructions I can find on how to install the branch?
> > > 
> > > 
> > > Unfortunately, you'd have to build the branch and run it manually using visual studio.
> > 
> > 
> > Tried building it in VS but it seems there is a solution missing that doesn't allow me to build the project, called "SBAuroraReactive.vcxproj"
> > I think I'll just wait for you guys to hopefully integrate this into the application itself. But I'm looking forward to it!
> 
> Oh, you probably forgot to pull the submodules. Running `git submodule update --init --recursive` would solve your issue.
> 
> As an update, I had aurora running with my changes all night and so far so good. I'll probably create the PR either today or tomorrow.

Ended up taking the branch and integrating it and now it looks like the Ducky is working great on the "Fine" setting.

Awesome work, thank you so much!

**Comment by umbreon222** [comment] 2021-01-01 19:41
Bad news, [my branch](https://github.com/umbreon222/Aurora/tree/bugfix/ducky_response_lag_2) causes my ducky shine 7 to hang after a random amount of time. I've tried everything I can think of to try and remedy this but I'm starting to think that the current support for ducky devices might need to be rewritten. I'll leave my branch available as a starting point for anyone who stumbles into this thread. I can't guarantee that I'll tackle this issue myself anymore since this has unfortunately become a bigger task. Sorry if I got any of your hopes up!

**Comment by craftycorvid** [comment] 2021-01-04 02:13
A workaround for this issue is to use the OpenRGB integration instead of the built-in Ducky support

**Comment by tibernero** [comment] 2021-01-04 02:56
> A workaround for this issue is to use the OpenRGB integration instead of the built-in Ducky support

So I actually started using openrgb with it but unfortunately it stills hangs after a certain period of time, requiring to restart aurora to fix it. It also is unable to detect the LEDs for the Calculator, Volume up, and Volume down keys.

**Comment by craftycorvid** [comment] 2021-01-04 03:17
I just submitted a PR to fix the Calc and Volume key issues. Haven't had it hang yet, but we'll see.

**Comment by Rukario** [comment] 2021-01-04 03:18
Sorry, how can I build Aurora with this patch? I'm on Windows 10, I'll tell you if my TKL board makes a difference

**Comment by tibernero** [comment] 2021-01-04 03:28
> 
> 
> I just submitted a PR to fix the Calc and Volume key issues. Haven't had it hang yet, but we'll see.

Thank you!

**Comment by craftycorvid** [comment] 2021-01-04 04:29
Just had it hang for the first time. It seems like OpenRGB can't talk to the keyboard anymore. I had to unplug and replug the keyboard to get the RGB to start working again. Seems like the issue might be on Ducky's side unfortunately.

**Comment by tibernero** [comment] 2021-01-04 15:13
> 
> 
> Just had it hang for the first time. It seems like OpenRGB can't talk to the keyboard anymore. I had to unplug and replug the keyboard to get the RGB to start working again. Seems like the issue might be on Ducky's side unfortunately.

Thanks so much for looking into it, though! I installed the openrgb fix branch you put out so at least all the LEDs are detected now. Ducky would really gain my respect if they updated their software to be more third party friendly. It is what it is!

**Comment by Lexevolution** [comment] 2021-01-22 18:59
I've tested my fix for this, so I hope it works for all of you :). [Here it is.](https://ci.appveyor.com/project/antonpup/aurora/builds/37392892/artifacts) And the pull request is above this comment.

**Comment by tibernero** [comment] 2021-01-22 19:14
> 
> 
> I've tested my fix for this, so I hope it works for all of you :). [Here it is.](https://ci.appveyor.com/project/antonpup/aurora/builds/37392892/artifacts) And the pull request is above this comment.

Just installed it now, and so far no problems. Thank you so much! :D

**Comment by umbreon222** [comment] 2021-01-22 19:20
Thanks for looking into this - I'll also join in on testing your branch. I'm going to leave it running all day to see if the device hangs and will report back end of the day. Fingers crossed 🤞

Update: Welp looks good to me! It's been a solid 10 hours and my keyboard hasn't hung at all. Nice!

**Comment by craftycorvid** [comment] 2021-01-24 09:11
This is it! I've been running it since yesterday and it hasn't frozen a single time.

**Comment by Rukario** [comment] 2021-01-26 07:25
I haven't encountered a single problem with TKL board either which is good news right? Logitech G910 seem to have problem reinitializing custom lighting after PC wakes up but maybe that's unrelated to this patch.

**Comment by Rukario** [comment] 2021-01-27 05:39
Something I've failed to notice... CPU usage is little too high to my liking, Ducky is on 15%, meanwhile Logitech G910 alone can be as low as 1%.

**Comment by ckosmic** [comment] 2021-07-08 19:34
I know this issue has basically been resolved with Rexevolution's patch, but I'd like to add this bit of information in case someone's wondering what may be causing it: for me the issue didn't start until I started using a Razer mouse.  I don't know if it's something with Razer products/Synapse specifically, but that seemed to be the cause of it for me.  After building Rexevolution's branch, everything was back to normal.

**Comment by Shangsou** [comment] 2021-08-04 07:45
> > I've tested my fix for this, so I hope it works for all of you :). [Here it is.](https://ci.appveyor.com/project/antonpup/aurora/builds/37392892/artifacts) And the pull request is above this comment.
> 
> Just installed it now, and so far no problems. Thank you so much! :D

I have the same issue with the lag/response time as mentioned above - but it looks like the build/fix you mentioned doesnt exist anymore

Does anyone have a link to the version that works? (Ducky shine 7)

**Comment by Lexevolution** [comment] 2021-08-04 08:03
> I have the same issue with the lag/response time as mentioned above - but it looks like the build/fix you mentioned doesnt exist anymore
> 
> Does anyone have a link to the version that works? (Ducky shine 7)

<s>This is the continuous integration builds that are automatically compiled/generated when a new pull request/fix is uploaded.

This includes my fix :) 

To download it, just click on the link and then click on the artifacts button. The .exe is the installer and the .zip is the portable version. 

https://ci.appveyor.com/project/antonpup/aurora</s>

**Read new comments below.**

**Comment by Lexevolution** [comment] 2021-08-04 08:17
Also if there's no artifacts anymore on the latest ci build (meaning no one has done anything with the code of aurora for over a month), message me on discord (you can find me as a developer on the aurora discord as `Lexevo#0876`) and I'll happily build the newest version and send it to you :)

**Comment by thedmd** [comment] 2021-08-05 06:42
I tested latest build `Aurora-v0.8.1+902-buhwdnlc.zip` and lag is still there.
![image](https://user-images.githubusercontent.com/1197433/128303615-6e25e912-26e6-4a2a-a476-7ea76e890342.png)

Is the fix on some different branch?

**Comment by Lexevolution** [comment] 2021-08-05 06:47
Ah yeah I realise that because my pull request with my fix in it hasn't been merged in to the dev branch, none of the later builds will actually have my fix in it. If you want, my fix is still available here if you want to build it yourself here: https://github.com/Lexevolution/Aurora/tree/fix/ducky-lag

Or my previous comment about me sending anyone the built version is still viable.

**Comment by thedmd** [comment] 2021-08-05 09:25
Build from this branch indeed works. Thanks!

**Closed as completed** 2021-09-01 17:02 UTC
Labels: Type: Bug
