### ISSUE TITLE
Rocket league (again)

### ISSUE THREAD

**Issue by MrDWilson** [antonpup/Aurora#262] opened 2016-12-18 20:23 UTC
Rocket league isn't working again! Love the program by the way

**Comment by MrDWilson** [comment] 2016-12-18 20:42
Also, the preview option does not work on any of the listed games, not sure if that's an issue on my end?

**Comment by antonpup** [comment] 2016-12-18 21:12
They should work... send over your latest log? Located in logs folder.

**Comment by MrDWilson** [comment] 2016-12-18 21:19
[2016_18_12 - Copy.txt](https://github.com/antonpup/Aurora/files/659668/2016_18_12.-.Copy.txt)

Here you go. Thank you for offering to help!

**Comment by MrDWilson** [comment] 2016-12-18 21:24
Okay, after looking over the logs I realised simply re-downloading would fix the preview error, which it did. So thank you for that, however rocket league is still broken.

**Comment by santosch** [comment] 2016-12-29 17:44
@antonpup I understand that updating pointer locations for RL is a really pain in the ass.
I did some research and found that guy here: 
https://github.com/d-karl/Rocket-League-Chroma-Control
He basically instructs users to start rocketleague with the -logs flag which opens an eventlog window beneath rl and than manages to read this window for logged events. (I've tested this, there really is plenty of information)
Perhaps that is something you want to look into

**Comment by antonpup** [comment] 2016-12-29 22:22
It looks like it can detect the current state (main menu, in-game), when you score a goal, when the countdown starts. Which is all nice, I can utilize it with effects. But it would mean that the boost amount, team scores, and current team will no longer work. I'll see if there's more in the log that I can harvest.

**Comment by MrDWilson** [comment] 2017-01-03 13:55
If using those logs meant that you would not have to update the pointers, I'm sure people would be willing to accept the compromise?

**Comment by s3cas** [comment] 2017-01-05 20:50
Well i was referred to this post but actually i already have check this and nothing works.

Still have problems related with Rocket League.

Thanks.

**Comment by brainbug89** [comment] 2017-01-06 00:03
@s3cas sorry if it was not clear: Aurora support for Rocket League is broken at the moment, because it's to time consuming to update the memory pointer for every patch of Rocket League.


@santosch 
> I did some research and found that guy here:
> https://github.com/d-karl/Rocket-League-Chroma-Control
> He basically instructs users to start rocketleague with the -logs flag which opens an eventlog window beneath rl and than manages to read this window for logged events. (I've tested this, there really is plenty of information)

He [stated](https://insider.razerzone.com/index.php?threads/rocket-league-chroma-control.11637/) at the Razer forum that his software no longer works, because:
> In one of the latest patches, Psyonix apparently changed the log level, meaning I can't detect events anymore.

He made no more updates since September.

@santosch Can you still read the logs for team, goal, countdown?

**Comment by s3cas** [comment] 2017-01-06 06:20
Hi @brainbug89 , 

The question is how can i make some steps with program only works with Razer?

I have try grab some info on Rzer forum like pointers and other stuff but seems with last update all mod's get a strange process.

I really like the mod's for another games but seems I will need to use a normal profile from LGS for Rocket League.

Thanks guys.

**Comment by santosch** [comment] 2017-01-06 15:32
@brainbug89 unfortunately, you are right.
While in menu the log is very talkative, but when i join a game there occurs almost nothing.
I only get a ~ "Update player stats" whenever i do something (goal, shot, etc.) and the only real event still logged is an "EpicSave" - but not if you do the save, only if a shot that you did is saved by another player.
Somehow strange, i actually think this should not be there any more as well.

I also experimented a bit with guessing of additional start params (-debug, -log=ALL etc.) to try to change the log level but as expected i was not successful with that.

This is making me really sad :'-(

**Comment by simon-wh** [comment] 2017-06-01 01:48
Duplicate of #185

**Closed by simon-wh** 2017-06-01 01:48 UTC
Labels: bug
