### ISSUE TITLE
 MasterKeys Pro L - Numpad 4 not lighting up

### ISSUE THREAD

**Issue by Nadeox1** [antonpup/Aurora#695] opened 2017-07-28 10:12 UTC
On the MasterKeys Pro L, the Numpad 4 button does not light up with any effect (It does if I disable Aurora, so it's working). In the Aurora visualization, the key appears lit.

I'm using the QWERTY (Italian) version.

Photo attached
![20170728_121029](https://user-images.githubusercontent.com/30523472/28713088-fe5c8ecc-738d-11e7-94b6-f655788f4010.jpg)

EDIT - In addition, the 'Pause' button seems to not be mapped correctly (as if it was located on the P4 button). In addition again, the P-keys do not light up.

EDIT 2 - Also the <> key isn't lit. It's located between SHIFT and Z

**Comment by brainbug89** [comment] 2017-07-28 10:49
Duplicate of #549

> EDIT 2 - Also the <> key isn't lit. It's located between SHIFT and Z
Could be a problem with the IT layout.

**Closed** 2017-07-28 15:51 UTC
