### ISSUE TITLE
LocalPCInfo

### ISSUE THREAD

**Issue by outofourlives** [antonpup/Aurora#513] opened 2017-03-27 17:39 UTC
Hey, i was just wondering if you're planing on adding more LocalPCInfo properties such as CPU temp/GPU load and temp/VRAM load/etc?
Sorry for submitting an issue, the program is just amazing. I love the layered approach in paricular, reminds me of After Effects.

**Comment by brainbug89** [comment] 2017-03-27 21:00
Duplicate of #68 and #469 :wink:

**Closed** 2017-05-14 17:52 UTC
