### ISSUE TITLE
Install Aurora wrapper patch for logitech does nothing

### ISSUE THREAD

**Issue by Dagda52** [antonpup/Aurora#702] opened 2017-08-01 00:06 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (GUI issue)

### Expected behavior:
Clicking on the option under the devices and wrappers option or the game with the same option should create a file in C:\Program Files\Logitech Gaming Software\SDK\LED with a message saying patch succesfull or something, or showing an error log if it failed

### Actual behavior:
Nothings happens, not even a warning or a error message, not even creates the corrsponding file

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open aurora elevated as admin or without privilegies
2. go to options/device & wrappers
3. Click on Install Aurora wrapper patch for logitech (applies for gaming profiles with the option too)
4. Nothing happens

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1 dev-2)

### Does the previous version of Aurora have this issue?
The previous version, (below 0.6.1-dev-2 is fine, even dev 1), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
there are no logs

**Comment by simon-wh** [comment] 2017-08-01 00:24
Duplicate of #699. See explanation there.

**Closed by simon-wh** 2017-08-01 00:24 UTC
