### ISSUE TITLE
Overwatch: Mouse Lag/Stuttering

### ISSUE THREAD

**Issue by GreenGhost21** [antonpup/Aurora#913] opened 2017-12-18 00:14 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

Cursor should move without interference

### Actual behavior:
Explain here what happened instead.

Cursor tends to "stutter", hindering movement significantly at seemingly random times. 

### How often does this problem occur?

This problem occurs... (So often it affects my performance as a player)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Going into a game of Overwatch with Aurora running

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1-dev3)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

Haven't tried previous versions, will try if needed.

**Comment by GreenGhost21** [comment] 2018-01-11 03:00
I hate to bump this, but it's been nearly a month with no response.

**Comment by simon-wh** [comment] 2018-01-20 00:50
Duplicate of #740

**Closed by simon-wh** 2018-01-20 00:50 UTC
