### ISSUE TITLE
Aurora not opening but using a lot of ram

### ISSUE THREAD

**Issue by LMH01** [antonpup/Aurora#1823] opened 2019-12-01 11:31 UTC
I have the following problem since Logitech G-Hub updated two days ago. Aurora will launch but not open. I can see the program running in the task-manager and using up a lot of ram. The ram usage will increase more and more after you have launched aurora
![aurora using a lot of ram](https://user-images.githubusercontent.com/35499705/69913314-8166aa00-1436-11ea-9574-0c51153772f3.JPG)
. Because of that the pagefile.sys file has grown to over 60GB. All this started after G-Hub updated to version 2019.11.29288. When I close G-Hub, restart my PC and open aurora, aurora will actually launch but without G-Hub i can't use it. Hopefully you are able to bring a hotfix soon, i have used aurora for 3 Years now and have not experienced anything like this.

**Comment by diogotr7** [comment] 2019-12-01 12:49
Duplicate of #1819

**Closed** 2019-12-01 12:49 UTC
