### ISSUE TITLE
Aurora with ASUS Aura Sync and NZXT Hue

### ISSUE THREAD

**Issue by iTzJackk** [antonpup/Aurora#942] opened 2018-01-06 13:57 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should work with Asus Aura Sync and NZXT Hue+ to control motherboards, rgb strips, case fans  and graphic cards

### Actual behavior:
---

### How often does this problem occur?

---

### Please describe the steps to reproduce this issue:
---

### What is the version of Aurora you are experiencing this issue with?

My version is... (Most recent)

### Does the previous version of Aurora have this issue?
The previous version, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2018-01-20 00:38
Duplicate of #329

**Closed by simon-wh** 2018-01-20 00:38 UTC
