### ISSUE TITLE
Rocket League Dynamic Not Working

### ISSUE THREAD

**Issue by DanteCodes** [antonpup/Aurora#571] opened 2017-05-21 06:23 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Rocket League)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (When I get into the game, the keyboard stays blue and doesn't change)

### Expected behavior:
I want it to change color dynamically through the game like it does when you preview it.

### Actual behavior:
It only stays blue and does not change at all.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launching Aurora
2. Launching Rocket League
3. Playing a game

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0-dev2)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0-b), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-05-21 15:19
duplicate of #185

**Closed by simon-wh** 2017-05-21 15:19 UTC
