### ISSUE TITLE
GPU and Motherboard Support?

### ISSUE THREAD

**Issue by ajmwagar** [antonpup/Aurora#654] opened 2017-07-13 19:36 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (MSI GeForce GTX 1060 6gb gaming X, Asus Prime Z270-AR (Motherboard))
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [] Visual bug
- [ ] Localization issue
- [x ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora
2. Look at GPU
3. Notice there are no settings available

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by ajmwagar** [comment] 2017-07-13 19:42
**Note** 
an SDK for ASUS Aura sync is available here: https://www.asus.com/campaign/aura/us/SDK.html#
another C# application, which controls MSI GPU LEDs (working) is here: 
https://github.com/Vipeax/MSI-LED-Tool 

The MSI tool is in active development, so be careful to implement it in a way that can be easily updated with the latest community-based themes.

If this gets done I will be super helpful. I would attempt it myself but I am busy with work.

**Comment by ajmwagar** [comment] 2017-07-13 19:46
Also, I just noticed that asking for aura sync is a duplicate. If it helps I found a prepacked .dll file with the SDK: https://github.com/opticalgenesis/AuraCUE

**Comment by simon-wh** [comment] 2017-07-17 14:27
Duplicate of #642 and #546. Please direct conversation related to those implementations to those issues.

**Closed by simon-wh** 2017-07-17 14:27 UTC
