### ISSUE TITLE
Allow LGS to takeover

### ISSUE THREAD

**Issue by SESNut** [antonpup/Aurora#533] opened 2017-04-16 06:40 UTC
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Is it possible to allow LGS auto profile select lighting profiles to still work for everything else that isnt the desktop?
I would like to use the desktop profile in aurora but the regular profiles for everything else from LGS

**Comment by VoronFX** [comment] 2017-04-17 12:22
Why use LGS one's?
You missing something that Aurora doesn't have? 
Maybe it's better to just add such support into Aurora? 
Personally I think there should be one controlling application, I wish Aurora could run without LGS at all.
Anyway making two application work together quiet problematic and a potential source of bugs.

**Comment by simon-wh** [comment] 2017-07-03 01:11
I could add a feature that would allow you to enter a list of applications where the devices would be disabled when those applications are at the foreground.

**Comment by simon-wh** [comment] 2018-09-01 00:37
Duplicate of #460

**Closed by simon-wh** 2018-09-01 00:37 UTC
Labels: enhancement
