### ISSUE TITLE
Skype bug

### ISSUE THREAD

**Issue by Johnnybeefcake** [antonpup/Aurora#86] opened 2016-07-29 16:28 UTC
Found a bug with Skype where the flashing notifier thing just stays even after viewing all messages and exiting out of skype completely. Seems to be linked with viewing new messages on another device before you view them on your comp

**Comment by antonpup** [comment] 2016-07-29 16:49
I was unable to reproduce this bug.

**Comment by Johnnybeefcake** [comment] 2016-08-01 23:03
Any way I can submit a log and would that help if I was able to?

**Comment by antonpup** [comment] 2016-08-01 23:04
If you can provide exact steps to replicate the issue, then I should be able to recreate it here. But using Skype on iOS did not result in messages remaining unread.

**Comment by Johnnybeefcake** [comment] 2016-08-03 16:53
Only just saw this. Got an Android phone and Skype on windows. I'll try to recreate it (haven't been able to recreate it intentionally) and give a step by step with version numbers

**Comment by Johnnybeefcake** [comment] 2016-08-13 07:39
Manage to recreate it. 
1) Get message
2) View message on phone
3) Keep skype open on phone (idk if this is mandatory or if just viewing the message is enough) for a few minutes.
4) Skype on PC should be orange as though there's an unread message but without the number of unread messages
5) Open the chat on PC
Skype Windows 7 Ultimate 64 bit :  v7.25.0.106 
Skype Android v5.0 : v5.2.0.61097
I think it might be important to mention I have view > split window view enabled on my PC.

**Comment by antonpup** [comment] 2016-08-13 16:26
It might be an android specific thing. When I view a message on my iPhone, it is instantly marked as read on my pc.

**Comment by Johnnybeefcake** [comment] 2016-08-13 17:38
It's marked as read on my PC, but it still thinks I have a message to view. I'll grab someone's iPhone and test it and post results

**Comment by antonpup** [comment] 2016-09-18 08:19
Closed. Feel free to reopen this issue once you have more information.

**Closed by antonpup** 2016-09-18 08:19 UTC
