### ISSUE TITLE
Spotify Equalizer

### ISSUE THREAD

**Issue by Xantha123** [antonpup/Aurora#135] opened 2016-09-03 09:37 UTC
Hi, 
is there an option to use the keyboard (K70 RGB Rapidfire) in an Equalizer mode when Spotify is playing (with different color settings)?

Cheers

**Comment by brainbug89** [comment] 2016-09-03 10:45
Duplicate of #34 

It's planned for a later version.

**Comment by antonpup** [comment] 2016-09-12 05:17
Like @brainbug89 said, this is a duplicate. I will be including a general visualizer for both microphone and speakers audio. I will close this issue, but please continue the discussion on issue #34 .

Thank you.

**Closed by antonpup** 2016-09-12 05:17 UTC

**Comment by apkright360** [comment] 2020-01-09 11:39
Try[ Spotify modified apk](https://thespotify.com/spotify-premium-apk/) for high-quality audio experience with that you do not need to any Equalizer
