### ISSUE TITLE
Visualizer not working after recent Realtek driver update

### ISSUE THREAD

**Issue by SavageBruh** [antonpup/Aurora#1890] opened 2020-01-18 04:07 UTC
### Expected Behaviour

Visualizer layer should work
### Actual Behaviour

Visualizer layer does not work
### Reproduction steps

Windows update installed the new Realtek audio drivers, and now the visualizer does not work at all. I tried rolling back the drivers to fix it but then I just get no sound.
### Frequency

Every time
### Aurora Version:

beta v0.7.2
### Previously an Issue?

Don't know

**Comment by diogotr7** [comment] 2020-01-18 13:20
Please upload a log from %appdata%\Aurora\Logs

**Comment by SavageBruh** [comment] 2020-01-20 01:31
@diogotr7 
[2020-01-19 17.25.09.log](https://github.com/antonpup/Aurora/files/4084084/2020-01-19.17.25.09.log)

**Comment by diogotr7** [comment] 2020-01-20 01:35
Duplicate of #1487

**Closed by diogotr7** 2020-01-20 01:35 UTC
Labels: Status: Information needed, Type: Bug
