### ISSUE TITLE
G810 Mediakeys and "locks" leds.

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#735] opened 2017-08-13 07:08 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
It should show the option to change the colors of the media keys -FOR G810 DEVICES- also (like play, skip, stop, game and brightness) and the numlock, capslock and scroll lock colors.
Shoud display them like the LGS does. Ex: http://imgur.com/a/o0CRY

### Actual behavior:
It don't

### How often does this problem occur?
This problem occurs... Basically when i open the program (?)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Done 

### What is the version of Aurora you are experiencing this issue with?
My version is... The latest (without being the dev ones)

### Does the previous version of Aurora have this issue?
I'm afraid so.

### Please include any logs, screenshots, or files that are related to this issue:
http://imgur.com/WPGdOjo (it doesn't show the media keys and neither the lock leds.)

**Comment by simon-wh** [comment] 2017-08-13 11:07
Duplicate of #711

**Closed by simon-wh** 2017-08-13 11:07 UTC
