### ISSUE TITLE
Problem with Aurora application launch

### ISSUE THREAD

**Issue by JurkaShev** [antonpup/Aurora#1964] opened 2020-04-19 16:00 UTC
I have downloaded Aurora today and haven't been able to use it.
### Expected Behaviour

Application loading up and app-window pops up.
### Actual Behaviour

I press the shortcut on my desktop, and the user account control comes up asking to verify that I want this program to make changes to the device and i click 'yes' which returns me to the desktop and after that nothing happens. Task manager shows no sign of Aurora .
### Reproduction steps

1. Click on desktop shortcut.
2. Accept on user account control.
### Frequency

Every time.
### Aurora Version:

0.7.2
### Previously an Issue?

I tried installing the 0.7.1 version but it just said to install the newest version and i proceeded to do so and the problem re-occured.

**Comment by diogotr7** [comment] 2020-04-19 16:07
Most likely a duplicate of #1895

**Closed by diogotr7** 2020-04-19 16:07 UTC
Labels: Type: Bug
