### ISSUE TITLE
support for asus spartha and claymore

### ISSUE THREAD

**Issue by OminiData** [antonpup/Aurora#891] opened 2017-11-29 23:48 UTC
I don't have any issues with this app.
I just want to know if it you guys could add support for asus spartha and claymore 

and i am not sure if it is possible but support for aquacomputer could be a cool feature too https://github.com/aquacomputer/plugin_sdk

**Comment by simon-wh** [comment] 2017-12-08 17:56
Asus pieces duplicate of #546 and AquaComputer duplicate of #129

**Closed by simon-wh** 2017-12-08 17:56 UTC
