### ISSUE TITLE
Aurora crashes

### ISSUE THREAD

**Issue by TristanPra** [antonpup/Aurora#1061] opened 2018-04-11 22:43 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Applications keeps running

### Actual behavior:
When Aurora is launched it randomly crashes and it takes me back to desktop if it's ingame but application keeps running in background

### How often does this problem occur?

This problem occurs. Every time i play but randomly

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Aurora
2. Play A game/use desktop
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1 dev4

### Does the previous version of Aurora have this issue?
The previous version, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
Error message 
https://imgur.com/a/8Ef6V

**Comment by brainbug89** [comment] 2018-04-14 20:50
Duplicate of #1046

**Closed** 2018-04-30 09:18 UTC
