### ISSUE TITLE
K95 Platinum Overwatch light bar issue.

### ISSUE THREAD

**Issue by jmeaker** [antonpup/Aurora#901] opened 2017-12-06 13:44 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The lightbar and the logo on the corsair k95 platinum to light up fully

### Actual behavior:
The only light on the bar is above the f10 key and the pause break key. Also theirs no light on the logo either. 

The G keys don't all light up but i believe theirs already a bug in for this as a general issue.

### How often does this problem occur?

Every time in overwatch.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch overwatch
2. Launch overwatch
3. On the main screen or in any character selection the problem happens

### What is the version of Aurora you are experiencing this issue with?

0.6.1-dev3

### Does the previous version of Aurora have this issue?
The lightbar is new to this version i believe?

### Please include any logs, screenshots, or files that are related to this issue:

https://imgur.com/xLXAIFu

**Comment by simon-wh** [comment] 2017-12-08 19:00
The G-Key issue will probably be sorted with the #759 PR that will be included in the next release. I'll have a look at the other bit where the lightbar is lighting up in areas where it shouldn't.

**Comment by simon-wh** [comment] 2018-02-16 20:12
Could you test out the build [here](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) and see if it is fixed?

**Comment by jmeaker** [comment] 2018-03-03 16:55
Hi, sorry for the delay. No I'm only getting the G1 key lighting up and now none of the lightbar or the logo are lighting up. 

https://imgur.com/a/W7MZ9

**Comment by jmeaker** [comment] 2018-03-03 17:29
Sorry, I should be more specific. This is in Overwatch and the lightbar and gkeys work fine otherwise

**Comment by FTWOblivion** [comment] 2018-06-28 00:41
i found a good personal solution to this, i know it is late. But go into your Aurora settings specifically for overwatch. There is a setting on the right called Exclude Keys, set it to exclude the one random G1 key that lights up. Then, under the overwatch profile, add a second layer and select the g keys and the light bar. It isnt a perfect solution as the light wont be dynamic with the rest of the keyboard. But at least you can set a neutral color for the light bar so it wont just be off. I personally used this color #FFF99E1A which is "Overwatch Orange" and i find it works well with every other color

**Comment by simon-wh** [comment] 2018-07-31 19:03
Could anyone who was experiencing this test if they still have it on v0.6.2?

**Comment by alecman3000** [comment] 2018-08-01 04:57
yes i'm still having the issue. only G1 is lighting up on v0.6.2b

**Comment by jmeaker** [comment] 2018-08-01 18:06
As mentioned above. Its still happening with v0.6.2b.

There is now no light on the lightbar where before it was lit in a few sections.

https://imgur.com/a/T4FSRut

Thanks for still trying to fix this! i appreciate the effort.

**Comment by Nevoska** [comment] 2019-01-27 03:02
The issue is still happening on build v0.6.3.
Keys G2-G6 and light bar does not work

**Comment by Gurjot95** [comment] 2019-02-03 21:14
#1341

**Closed by Gurjot95** 2019-02-03 21:14 UTC
Labels: bug
