### ISSUE TITLE
Aurora Launch Crash

### ISSUE THREAD

**Issue by ArsamS** [antonpup/Aurora#630] opened 2017-07-01 00:43 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The program should start up.
### Actual behavior:
Launches in task manager with Aurora updater, but closes immediately.
### How often does this problem occur?

This problem occurs... every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Aurora
2. ???
3. No profit

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
Didn't have any previous versions, first time installer.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/rfSXPXCV

I don't have MSI Afterburner or any other programs that can be stopping it, apart from Logitech G Software and Windows Defender but I closed both and the program still wouldn't open.

**Comment by simon-wh** [comment] 2017-07-01 00:58
Duplicate of #605. Please post any follow up in that issue.

**Closed by simon-wh** 2017-07-01 00:58 UTC
Labels: duplicate
