### ISSUE TITLE
Logitech G910 doesnt work in RL.

### ISSUE THREAD

**Issue by andsrs** [antonpup/Aurora#1156] opened 2018-06-28 06:46 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [X] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

I wanted LED effects for Rocket League... doesnt work :(

### Actual behavior:
Explain here what happened instead.

on keyboard lights just color of blue team. when im in game doesnt happen anything :(

### How often does this problem occur?

This problem occurs... (Fill in here)

always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. buy g910
2. launch aurora
3. launch rl
4. cry

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

last

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

of course

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

just try yourself :(

**Comment by diogotr7** [comment] 2018-06-28 11:56
yep it hasn't worked for a while and unfortunately I don't think its going to work again. I tried finding the pointers and they seem to change everytime you enter a match. 
I got the boost working in training but if you exit training and come back it breaks. Unfortunately, not much we can do :(.

**Comment by simon-wh** [comment] 2018-06-28 15:21
duplicate of #185

**Closed by simon-wh** 2018-06-28 15:21 UTC
