### ISSUE TITLE
Discord Support

### ISSUE THREAD

**Issue by KillMeImSalty** [antonpup/Aurora#613] opened 2017-06-20 02:23 UTC
Today Discord announced their collaboration with Logitech: https://twitter.com/discordapp/status/876937721616375808 I thought it would be cool to have it in Aurora since there is already support for Skype, although it's slowly getting replaced by teamspeak and discord etc.

**Comment by simon-wh** [comment] 2017-06-20 08:15
Duplicate of #297

**Closed by simon-wh** 2017-06-20 08:15 UTC

**Comment by brainbug89** [comment] 2017-06-20 14:16
#297 was closed because it didn't seemed to be possible, but now with https://twitter.com/LogitechG/status/876934012161241089 shouldn't it work with the Logitech wrapper?

**Comment by thu2468** [comment] 2017-07-04 06:34
@simon-wh The applet path is C:\Program Files\Logitech Gaming Software\ArxApplets
