### ISSUE TITLE
Rocket League (again)

### ISSUE THREAD

**Issue by SomethingOrange** [antonpup/Aurora#227] opened 2016-12-02 19:53 UTC
Doesn't seem to work again, just plain ol' blue like last time. Thank you so much for developing this though, if there is any way I can help or donate to you, link me :)

**Comment by brainbug89** [comment] 2016-12-02 21:19
See README.md for donation link: https://github.com/antonpup/Aurora#donations

**Comment by simon-wh** [comment] 2017-03-21 21:10
Closing due to duplicate of #262

**Closed by simon-wh** 2017-03-21 21:10 UTC
Labels: bug
