### ISSUE TITLE
[GameSupportRequest] Team Fortress 2

### ISSUE THREAD

**Issue by manskou** [antonpup/Aurora#258] opened 2016-12-17 14:10 UTC
It should be easy because tf2 runs on the same engine as csgo.

Ultimately, it could display time related events (such as ubercharge precent, or spy's cloak)

Basic things like team color, respawn, health, and ammo should be the same as in cs.

**Comment by brainbug89** [comment] 2016-12-17 14:35
CS:GO and Dota 2 are using [GSI](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration). It's a SDK to support third party apps like Aurora.
TF2 (and other Source Engine games) doesn't use GSI.

**Comment by manskou** [comment] 2016-12-17 14:42
So integration with tf2 would require valve implementing GSI to tf2 right?

**Comment by brainbug89** [comment] 2016-12-17 16:29
Yes, or some other sort of data export or RGB keyboard support. Most games directly conrolling RGB keyboard devices.

**Comment by antonpup** [comment] 2016-12-17 19:04
Duplicate of #120 

Information cannot be safely retrieved from the game.

**Closed by antonpup** 2016-12-17 19:04 UTC
