### ISSUE TITLE
Diablo 3 not working (at all)

### ISSUE THREAD

**Issue by kingcailan** [antonpup/Aurora#853] opened 2017-11-03 05:31 UTC
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Not working at all)

### Expected behavior:
Patch Diablo 3, launch Diablo 3, Lighting Responds

### Actual behavior:
I patched the game, launched it, and the desktop profile stayed active.

### How often does this problem occur?
Every time the game is launched.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch Game
2. Launch Game
3. Nothing happens.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
Unknown.

My devices are all Logitech. I'm using a G810 Orion Spectrum, G502 Proteus Spectrum, and a G633 Artemis Spectrum.

**Comment by simon-wh** [comment] 2017-11-03 11:05
Duplicate of #539

**Closed by simon-wh** 2017-11-03 11:05 UTC
