### ISSUE TITLE
Add Logitech g513 to database. And Eso

### ISSUE THREAD

**Issue by tbagwell** [antonpup/Aurora#1177] opened 2018-07-17 22:30 UTC
Please add g513 from Logitech. And also add Elder scrolls online, Fallout 4 also for profiles.

**Comment by simon-wh** [comment] 2018-07-18 12:21
G513 is a duplicate of #1073 
ESO is a duplicate of #448 
Fallout 4 is a duplicate of #927

**Closed by simon-wh** 2018-07-18 12:21 UTC
