### ISSUE TITLE
Support for online profiles

### ISSUE THREAD

**Issue by jdubnz** [antonpup/Aurora#178] opened 2016-10-11 22:03 UTC
Not an issue, just a possible enhancement. (or I'm just incompetent) 

Is there any way to provide support for a profile found online? SO we can download Razer, Corsair, logitech profiles etc...

Eg. If I found a corsair profile for Witcher 3, is there a way of making that work with Aurora on a Logitech keyboard? That would greatly increase the number of games that the keyboard can respond to in-game events.

**Comment by antonpup** [comment] 2016-10-11 22:12
At the moment, no. It is planned to convert proprietary profiles to Aurora profile. But it isn't a priority at the moment.

**Comment by jdubnz** [comment] 2016-10-11 22:14
Awesome, cheers for the quick feedback. Keep up the good work. And let me know if you need help with RL pointers again :)

**Comment by brainbug89** [comment] 2016-10-12 12:19
> That would greatly increase the number of games that the keyboard can respond to in-game events.

How that?

**Comment by the27club** [comment] 2016-10-22 14:24
i second this!

**Comment by Pandry** [comment] 2016-10-25 06:27
A server should be used, so...
It would cost some money, at least if the server is not gifted...

**Comment by simon-wh** [comment] 2018-09-01 00:51
Duplicate of #429

**Closed by simon-wh** 2018-09-01 00:51 UTC
Labels: enhancement
