### ISSUE TITLE
MK750: Aurora stutters effects stuttering

### ISSUE THREAD

**Issue by papi35** [antonpup/Aurora#1326] opened 2018-11-09 20:32 UTC
Keyboard: Cooler Master MK750

Hello,

The lightning effects, even if they aren't interactive are stuttering and freezing whenever you press several keys in a row. As I'm typing this sentance the effects have stoppped and started again multiple times. This only happens when you write or click a lot of buttons.

Thanks!

**Comment by papi35** [comment] 2018-11-11 03:46
Solved by uninstalling cooler master portal (cooler master software)

**Comment by Zazama** [comment] 2018-12-19 20:50
>  Solved by uninstalling cooler master portal (cooler master software)

Interesting, did it really fix this problem for you? I'm still having the issue after uninstalling all Cooler Master Software.

**Comment by simon-wh** [comment] 2019-01-21 16:42
Seems to be duplicate of #1291

**Closed by simon-wh** 2019-01-21 16:42 UTC
