### ISSUE TITLE
Rainbow 6: Siege Profile

### ISSUE THREAD

**Issue by gabelheinz** [antonpup/Aurora#163] opened 2016-10-03 16:53 UTC
Hi, great work on the Project! I've waited almost 2 years for that kind of game-support :)
I'd like to request a Rainbow 6: Siege profile.

My idea would be to make ammo, life, flash and fire CS:GO-ish together with a filling white bar for building/using things.
When injured the keyboard could be all dark-red and the closer you come to death the more keys are getting dark.
Another great feature would be a random colour flashing keyboard if the drone got jammed by Mute.
The six function keys over the arrow keys could shine in the colour of the chosen operator (i.e. yellow for the GSG9 or orange for the FBI).
When using a G910 the G-keys could also show how many consumables or fortifications are left.

Thats it, keep going with your nice work.
Sincerely gabelheinz

**Comment by goofeezy** [comment] 2016-12-26 02:45
still waiting please :D

**Comment by brainbug89** [comment] 2017-01-04 13:45
Duplicate of #92 
Seems to be not possible.

**Closed** 2017-06-20 08:35 UTC
Labels: enhancement, game support
