### ISSUE TITLE
Razer Chroma Layer broke after trying to reset layer

### ISSUE THREAD

**Issue by holdenlessard** [antonpup/Aurora#2017] opened 2020-05-17 17:01 UTC
### Expected Behaviour
Overwatch was not working right on my Logitech keyboard, and I thought by resetting the Razer Chroma Layer, it would fix the issue and work.

### Actual Behaviour
Unless it's hero select in Overwatch (which doesn't even display the right hero color), the Razer Chroma Layer glitches through a multitude of colors. It also happened while playing Terraria.

### Reproduction steps
Reset the Chroma LAyer while in Overwatch.

### Frequency
Every time.

### Aurora Version:
beta v0.7.2

### Previously an Issue?
Don't know

**Comment by diogotr7** [comment] 2020-05-17 17:02
Duplicate of #1960

**Comment by diogotr7** [comment] 2020-05-17 17:02
This is not caused by resetting the layer at all, it's due to the newer versions of the chroma sdk breaking aurora's method

**Closed by diogotr7** 2020-05-17 17:02 UTC
Labels: Type: Bug
