### ISSUE TITLE
aurora constantly accessing my microphone

### ISSUE THREAD

**Issue by bettafish04** [antonpup/Aurora#1740] opened 2019-10-03 15:58 UTC
### Expected Behaviour
microphone not being accessed while not having microphone level as lighting effect

### Actual Behaviour

it accesses it nonetheless
### Reproduction steps

1. install aurora
### Frequency

always
### Aurora Version:

0.7.0-rc2
### Previously an Issue?

i dont know

**Comment by Wibble199** [comment] 2019-10-04 10:19
This functionality has been present for a while but it's only due to the recent Windows 10 update that the microphone icon is appearing.

In the current v0.7.0 release candidates (both 1 and 2), there is an option in the settings to turn this feature off (and it will be off by default).

Duplicate of #1578, #1672.

**Closed by Wibble199** 2019-10-04 10:19 UTC
Labels: bug
