### ISSUE TITLE
crash every time i open

### ISSUE THREAD

**Issue by estevanlandivar** [antonpup/Aurora#1088] opened 2018-05-07 20:30 UTC
### What are you experiencing an issue with?

- x[ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x ] Other, (crashing)

### What kind of an issue is it?

- [ x] Crash
- [ x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
should just open normally since i reinstalled 4 times
### Actual behavior:
crashes every time i open. the lights still work until i click ok on the message sayin it crashed
### How often does this problem occur?
everytime
This problem occurs... (everytime i open)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
open then crash
1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... latest stable version

### Does the previous version of Aurora have this issue?
that is the first version i use
### Please include any logs, screenshots, or files that are related to this issue:
https://imgur.com/5IbFUnq

For logs, you can use: http://pastebin.com/
For screenshots, you can use: https://imgur.com/5IbFUnq
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2018-05-08 08:45
Duplicate of #1039

**Closed by simon-wh** 2018-05-08 08:45 UTC
