### ISSUE TITLE
GTA V all white (again)

### ISSUE THREAD

**Issue by TheKingofChicken** [antonpup/Aurora#1295] opened 2018-10-08 21:38 UTC
### How often does this problem occur?

This problem occurs... (Fill in here)
Whenever GTA 5 is open
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.oppenning GTA 5
2. this section won't be useful
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
The Latest stable one, 0.6.3
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue
I just  installed, so I can't know

**Comment by simon-wh** [comment] 2018-10-13 17:09
Duplicate of #1015

**Closed by simon-wh** 2018-10-13 17:09 UTC
