### ISSUE TITLE
Pretty Sure No Logitech Game Effects Work on my Corsair K70

### ISSUE THREAD

**Issue by FTWOblivion** [antonpup/Aurora#1050] opened 2018-04-02 09:14 UTC
### What are you experiencing an issue with?

- [X] Aurora
- [ x] Aurora supported game, (Fill in the game)
- [ x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ x] Performance problems
- [ x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Pretty much every game works except for Logitech games

### Actual behavior:
Mirror's Edge, GTA V is just a pure white keyboard. no effects, no matter what i do
### How often does this problem occur?
<!-- Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Corsair K70
2. Mirror's Edge
3. Don't Profit

### What is the version of Aurora you are experiencing this issue with?
6.1
### Does the previous version of Aurora have this issue?
Not Sure

**Comment by simon-wh** [comment] 2018-05-05 16:27
Duplicate of #1052

**Closed by simon-wh** 2018-05-05 16:27 UTC
