### ISSUE TITLE
Tray icon not showing up

### ISSUE THREAD

**Issue by argente69** [antonpup/Aurora#905] opened 2017-12-12 00:16 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (The tray icon does not show up)

### Expected behavior:
it should be in the tray bar

### Actual behavior:
when i start aurora, the icon appears in the tray but suddenly disappears

### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing th

is issue with?

My version is... (0.6.1-dev3)

### Does the previous version of Aurora have this issue?
i always had this issue

**Comment by Wuestengecko** [comment] 2017-12-20 22:38
I might be experiencing the same problem. When starting, I don't see the tray icon at all; the only way to make it work again seems to be deleting Aurora's %APPDATA% folder (which isn't practical for obvious reasons).
Also I noticed that the process starts to eat up more and more RAM, adding about 5MB every second or so (I let it sit for a while once and it reached over 2 GB before I killed it).

Windows' Resource Monitor says that "at least one thread of Aurora.exe is waiting". Further analyzing the process with the Sysinternals Process Explorer, the thread 9300 (which is waiting, according to resmon) has this call stack:
```
ntdll.dll!NtWaitForMultipleObjects+0x14
KERNELBASE.dll!WaitForMultipleObjectsEx+0x106
combase.dll!CoDecrementMTAUsage+0x792
combase.dll!NdrExtStubInitialize+0x39bf
combase.dll!CoTaskMemFree+0x637
combase.dll!NdrExtStubInitialize+0x2452
combase.dll!CoGetApartmentType+0x25c
RPCRT4.dll!NdrClientCall3+0x5f7
combase.dll!NdrOleInitializeExtension+0x2cd
combase.dll!ObjectStublessClient32+0xfc32
combase.dll!CoGetStandardMarshal+0x4289
combase.dll!CoGetStandardMarshal+0x436f
clr.dll!TranslateSecurityAttributes+0xc3267
clr.dll!TranslateSecurityAttributes+0xc6d66
clr.dll!TranslateSecurityAttributes+0xc8f97
clr.dll!NGenCreateNGenWorker+0xf2524
clr.dll!StrongNameFreeBuffer+0x27431
clr.dll!DllCanUnloadNowInternal+0x70f56
clr.dll!DllCanUnloadNowInternal+0x70ba1
clr.dll!LogHelp_TerminateOnAssert+0x1bd1
clr.dll!LogHelp_TerminateOnAssert+0x1b4c
clr.dll!LogHelp_TerminateOnAssert+0x1a8a
clr.dll!ClrCreateManagedInstance+0x45fa
clr.dll!GetMetaDataPublicInterfaceFromInternal+0x53af
KERNEL32.dll!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

The thread 3476, which the above one is waiting for (if I understand correctly), has this stack:
```
win32u.dll!NtUserMessageCall+0x14
USER32.dll!SendMessageW+0x279
USER32.dll!SendMessageA+0x55
SDKDLL.dll!SetKeyCallBack+0x2b38f
SDKDLL.dll!SetKeyCallBack+0x2ba7d
SDKDLL.dll!SetKeyCallBack+0x2bc06
SDKDLL.dll!SetKeyCallBack+0x2bd40
SDKDLL.dll!SetKeyCallBack+0x1f86
SDKDLL.dll+0x1fbf
SDKDLL.dll!IsDevicePlug+0x65
[Native Frame: IL Method without Metadata]
[Managed to Unmanaged Transition]
Aurora.exe!Aurora.Devices.CoolerMaster.CoolerMasterDevice.SwitchToDevice+0x2f
Aurora.exe!Aurora.Devices.CoolerMaster.CoolerMasterDevice.Initialize+0xe8
Aurora.exe!Aurora.Devices.DeviceManager.Initialize+0xd3
Aurora.exe!Aurora.Program.Main+0xb74
[Unmanaged to Managed Transition]
clr.dll!LogHelp_TerminateOnAssert+0xe83
clr.dll!LogHelp_TerminateOnAssert+0xd1d
clr.dll!LogHelp_TerminateOnAssert+0x1425
clr.dll!SetRuntimeInfo+0x10f8
clr.dll!SetRuntimeInfo+0x1a3e
clr.dll!SetRuntimeInfo+0x18fd
clr.dll!SetRuntimeInfo+0x12b0
clr.dll!SetRuntimeInfo+0x122e
clr.dll!CorExeMain+0x14
mscoreei.dll!CorExeMain+0x6d
MSCOREE.DLL!CorExeMain+0x6c
KERNEL32.dll!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

Judging from the stack, it seems to be waiting for a CoolerMaster SDK - but I don't even own a CoolerMaster RGB device (all my RGB capable devices are made by Razer, in case that matters).

None of the above threads actually consumes CPU time (according to process explorer). There are however in total 12 other threads that add up to about 0.5% CPU usage. All of these have the clr.dll or the SDKDDL.ddl file in their stack - for some reason procexp deems these dlls important enough to show them in the thread overview window, see: https://imgur.com/a/oMkUw

Interestingly enough, the lighting effects actually do work.

Occuring for the first time with `Aurora 0.6.1-dev3`, previously installed version was `0.6.1-dev2`.

**Comment by simon-wh** [comment] 2018-01-20 00:00
Duplicate of #814

**Closed by simon-wh** 2018-01-20 00:00 UTC
