### ISSUE TITLE
More LED light support

### ISSUE THREAD

**Issue by Wolfieeewolf** [antonpup/Aurora#599] opened 2017-06-12 06:43 UTC
Any chance of support for LED Strips and RGB LED lights ie HUE or Mi lights or the Philips Ambx. Add support for Case lights would be good to ASUS Aura leds and NZXT? Would be great to get all my RGB lights linked in one program.

**Comment by brainbug89** [comment] 2017-06-12 23:34
Asus aura is duplicate of #546 
NZXT Hue+ is duplicate of #132 
For Mi Light I couldn't find any SDK or API, so doesn't seem possible.
For Philips Ambx there seems to be an very old SDK, so it would be possible.

**Comment by Wolfieeewolf** [comment] 2017-06-15 12:57
Mi Light API - http://www.limitlessled.com/dev/
Ambx SDK - http://ambx.exsanio.de/

With the Ambx SDK you can also control the add-on fans and rumble pad. I'm sure you can work in some awesome effects that go along with the many already supported games. I know it's old tech but it does add a lot to games. Even if it looks a little dumb.

**Comment by Wolfieeewolf** [comment] 2017-06-17 12:10
https://github.com/ZodiusInfuser/AuroraSynesthesia/releases

Might be something you could add somehow for AMBX support

**Comment by Wolfieeewolf** [comment] 2017-06-27 14:20
So I was thinking about this the other day that if you could some how reverse engineer the Ambx SDK to work with any lighting source IE led strip or atmo orb you could in theory make your own Ambx lighting system. If this is possible then you could play many of the already Ambx enabled games with hardware of you choice. The other cool thing that Ambx can do it 3D positional lighting . That mean say you playing a FPS and you walk up to a light source on the wall. Well if you had LED lights setup around you in a 360 type pattern then when you walk passed the light it would move to lights on the side and then to the lights behind you putting you "in the game". I'm sure you could go wild with what kinds of effects you could do from spinning lights around you or making your audio visualizer look really neat. The list goes on and on. Anyways just a idea if you were interested in doing something like that

**Comment by Wolfieeewolf** [comment] 2017-07-28 12:38
http://mattcallaghan.blogspot.com.au/2016/01/ambx-glow.html

**Comment by Wolfieeewolf** [comment] 2017-11-01 11:51
Was looking through Github the other day and found this 

https://github.com/SonicBoom89/ShooterAmbx

It might be a way to get something working with the Ambx lights and such. Appears it just grabs keyboard and mouse clicks to get the fans and rumble pad working. I guess you could even try using it for the other RGB stuff as well.  You would get a heap of games working with it quite quickly. Guess you then could make some custom effects for shooters, RTS games, beatém ups and the like.  Might make for some cool effects for alerts and notifications with the fans and rumble as well. Could some how link it to keys or make a generic item link like the mouse has but for fan and rumble. Could then do things like Flashbangs make the fans go. Boosts in rocket league rumble when ready or health low in CSGO rumbles and turns on the fans. Could be use for things like CPU usage high or the EQ maxes out. I'm sure there is heaps of things that you could do. If you hack the code somewhat I'm sure you could get it working it so you don't have to use Ambx tech and could make you own fans and rumble pads using an arduino or something. Maybe even just get a normal game pad to rumble. something like https://github.com/Tominator2/MotorController or https://github.com/lucasw/joy_feedback_ros might get it working. Could use some kind of PWM fan controller the run the fans as well. Anyways, I have looked at the code and sort of understand what it's doing but not having any real hands on with coding I'm at a loss are where I would start to try and make this work. Thought you or someone out there in coding land might be able to make something out of it.

**Comment by sausje** [comment] 2018-03-25 13:51
Since this issue got carried away into multiple directions, I was wondering if you are still planning to add the Mi-Light/LimitlessLED integration to Aurora?
(SDK: http://www.limitlessled.com/dev/ )

I recently bought their LED strips for in my room with the wifi module, would love it to be in sync with AlienFX for example when playing League.

**Comment by simon-wh** [comment] 2018-03-28 18:53
@sausje I'm going to add support for everything I can once I finish the reworked device layout system (which is on hold because I currently have the flu)

**Comment by sausje** [comment] 2018-03-28 18:56
Thank you, really happy to hear that. Good luck getting better!

**Comment by kekkokk** [comment] 2018-04-20 19:44
I was "able" to implement Aura support but with lots of caveat.
If you would like to check out and contribute to makes the other Brands works in x86 please don't hesitate to contact me

https://github.com/kekkokk/Aurora/releases/tag/v0.6.1-dev4-asus

**Comment by Wolfieeewolf** [comment] 2018-11-18 21:52
SDK for you

[amBX SDK (February 2009).zip](https://github.com/antonpup/Aurora/files/2593276/amBX.SDK.February.2009.zip)

**Comment by Wolfieeewolf** [comment] 2018-11-18 22:01
amBX For VB.net

[ambx.zip](https://github.com/antonpup/Aurora/files/2593284/ambx.zip)

**Comment by Gurjot95** [comment] 2019-02-03 21:12
All of the above devices are already working, or WIP. Also, duplicate.

**Closed by Gurjot95** 2019-02-03 21:12 UTC
Labels: sdk support
