### ISSUE TITLE
Discord Support?

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#742] opened 2017-08-16 16:11 UTC
I was wondering if we could have discord support, as it apparently has a lighting API now.
Steelseries is already using it.

**Comment by simon-wh** [comment] 2017-08-16 16:24
Duplicate of #297, the case for steel series might be the same as Logitech, but I'll check when I'm home and post details in the mentioned issue

**Closed by simon-wh** 2017-08-16 16:24 UTC
