### ISSUE TITLE
Memory leak issue in most recent beta

### ISSUE THREAD

**Issue by twalts** [antonpup/Aurora#833] opened 2017-10-15 00:10 UTC
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora runs normally.

### Actual behavior:
Aurora makes my computer freeze because it's using a massive amount of memory.

### How often does this problem occur?

This problem occurs every time I run Aurora for longer than 15 minutes.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Turn on Aurora.
2. Let my desktop profile run for about 10-15 minutes. (I have a lot of layers, can list them if I need to)
3. Computer freezes as it warns me my memory is getting too low and I must quit Aurora.

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
AFAIK, the previous version did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-10-15 14:28
Duplicate of #758

**Closed by simon-wh** 2017-10-15 14:28 UTC
