### ISSUE TITLE
Rocket League

### ISSUE THREAD

**Issue by s3cas** [antonpup/Aurora#321] opened 2017-01-05 19:50 UTC
Hello guys,

I have download and install the Aurora setup and i could set the Skype interface and the OverWatch interface but i can't fix the problems with Rocket League in my Logitech G910.

There is any Dev or someone who knows how to fix this issue?

Thanks a lot,
s3cas

**Comment by brainbug89** [comment] 2017-01-05 20:27
The Rocket League memory pointers need to updated.

Duplicate of #262

**Comment by santosch** [comment] 2017-01-05 20:45
As Brainbug said, the pointers would need updating. Since this happens at every RocketLeague update, this will no longer be actively supported by Anton. But he is looking into alternate methods to get some game info to create effects.
If you know how (i, unfortunately, do not) to find the correct pointers, there is a file Pointers/RocketLeague.json in your Aurora folder where you can change them. If you find the correct ones, a PR is highly appreciated I think.

**Comment by simon-wh** [comment] 2017-03-20 08:31
Duplicate, closing.

**Closed by simon-wh** 2017-03-20 08:31 UTC
