### ISSUE TITLE
The memory issue persists even after running twice the command. (minor issue: no logs)

### ISSUE THREAD

**Issue by andrixbooom** [antonpup/Aurora#866] opened 2017-11-12 11:49 UTC
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
it shouldn't eat up my RAM, slowing my computer down a lot. It should also create logs in the designated folders.

### Actual behavior:
It eats up my RAM, slowing my computer to the point that it takes a whole minute to load up the task manager, and after running twice the command lodctr /R, in a command prompt run as administrator, it works fine until i restart my pc.
It doesn't create logs in the designated folder, as it wasn't present. All I did was manually create it, hoping that in someway it would. It does not.

### How often does this problem occur?
This problem occurs everytime I restart my computer.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
Boot the computer

### What is the version of Aurora you are experiencing this issue with?
0.6.1. -dev3

### Does the previous version of Aurora have this issue?
Never had this problem before, but I jumped straight forward from v 0.6.0. to -dev3.

### Please include any logs, screenshots, or files that are related to this issue:
I have no logs, and I am currently trying to fix that by reinstalling the program from scratch.
https://imgur.com/bB7Yn5m

**Comment by simon-wh** [comment] 2017-11-12 16:01
Duplicate of #758

**Closed by simon-wh** 2017-11-12 16:01 UTC
