### ISSUE TITLE
ETS2/ATS Logitech Lighting Compatibility

### ISSUE THREAD

**Issue by Sweren** [antonpup/Aurora#917] opened 2017-12-19 23:56 UTC
Hello and thank you for giving this space to request compatibility with other apps
I have seen that there are other third-party software that supports ETS2 and ATS such as "Artemis" and "Logitech G910 Light Enabler for ATS and ETS2" but both are OUTDATED and currently do not work.
These software use these SDKs:
https://github.com/Funbit/ets2-telemetry-server
https://github.com/nlhans/ets2-sdk-plugin#installation

Here I leave a screenshot and the link of these software 
Artemis: 
https://imgur.com/a/BYFdi
https://github.com/SpoinkyNL/Artemis
https://github.com/Funbit/ets2-telemetry-server

Light Enabler: https://www.reddit.com/r/trucksim/comments/45nnm0/logitech_g910_light_enabler_for_ats_and_ets2/
https://github.com/nlhans/ets2-sdk-plugin#installation

**Comment by simon-wh** [comment] 2018-01-19 23:54
ETS2 is duplicate of #136

**Closed** 2018-01-19 23:55 UTC
Labels: duplicate
