### ISSUE TITLE
Diablo 3 not lighting up g810 but g900 lights up fine

### ISSUE THREAD

**Issue by Mikewl** [antonpup/Aurora#539] opened 2017-04-18 16:16 UTC
- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [x] Other, (Fill in another issue here)
Diablo 3 using the Razer wrapper

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Both the G810 and G900 should light up in red in Diablo 3 with the ability keys being highlighted. The colour should change as well when certain abilities are used. This works fine with the g900 but the g810 only highlights the abilities. The blanket colouring is missing.

### Actual behavior:
The g900 lights up in full colour while the g810 only has white keys for the abilities with the rest of the keyboard going dark.

### How often does this problem occur?
Every time the game is run.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Using both the g900 and g810
2.  Run diablo 3
3.  Notice only the g900 is red

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6b

### Does the previous version of Aurora have this issue?
It is unknown whether the previous version has an issue.

**Comment by jamescho7** [comment] 2017-04-29 01:36
This happens for me too!

**Comment by antonpup** [comment] 2017-04-30 01:41
Downloading Diablo 3 to test.

**Comment by antonpup** [comment] 2017-05-01 18:48
Loaded up Diablo 3 via Razer wrapper. My Q lit up white and turned off when Q was on cooldown. Mouse lit up red.

From what I understand, the entire keyboard is also supposed to light up red. Anything else wrong with it?

**Comment by jamescho7** [comment] 2017-05-01 18:56
The keyboard should also turn gold or green when legendary or set items drop.

**Comment by antonpup** [comment] 2017-05-01 22:40
Playing a bit more, the game only sends lighting regarding the action keys and mouse lighting. The mouse always stays red, it doesn't change color based on drops. So.. I don't know. From my side it looks like they're either using a newer SDK, so wrapper doesn't have some commands, or the game itself doesn't send that data over. At my first glance, it seems to be working properly, no errors.

**Comment by antonpup** [comment] 2017-05-01 22:42
One thing to note is that I am playing this on the Starter Edition. That could also be a reason for fewer lighting effects.

**Comment by jamescho7** [comment] 2017-05-02 04:21
Hm. I don't think the game edition should matter. 

> game only sends lighting regarding the action keys and mouse lighting

Doesn't this mean that the G900 should be dark also with the exception of those keys? In any case, thank you for looking into this!

**Comment by antonpup** [comment] 2017-05-02 04:31
> Doesn't this mean that the G900 should be dark also with the exception of those keys?

Well no. The game specifically sets the color of the mouse to red. But it doesn't seem to do much beyond that.

I have also plugged in and tested my Corsair Strafe. Lighting works as described there. So I will either look into updating the Razer Wrapper to support this, or I will make a CUE wrapper to add to the list of supported wrappers and Diablo 3 will be one of the first supported.

**Comment by jamescho7** [comment] 2017-05-02 04:33
Oh oops -- I thought G900 was a keyboard model. I think the OP was talking about G910.

Both the G810 and G900 should light up in red in Diablo 3 with the ability keys being highlighted. The colour should change as well when certain abilities are used. This works fine with the g900 but the g810 only highlights the abilities. The blanket colouring is missing.

**Comment by ersan** [comment] 2017-05-08 07:29
Also noticed this when I went to play Diablo 3 today, it's only lighting up 1-2-3-4 and Q keys (with cooldowns) - the red glowing and item drop features aren't working.

Using a Razer Blackwidow keyboard.  Also deleting the Wrapper SDK files from the Diablo 3 directory doesn't seem to disable piping the commands through Aurora.

**Comment by Mikewl** [comment] 2017-07-23 14:11
any progress on this? I can confirm that it is setting the keyboard red without aurora in a normal razer keyboard

**Comment by simon-wh** [comment] 2017-07-23 14:14
@Mikewl You could try the [latest development release](https://github.com/antonpup/Aurora/releases) as there have been changes to the wrappers since 0.6.0b which might fix the issue.

**Comment by Mikewl** [comment] 2017-07-23 14:54
The wrappers are flat out failing for the latest development release and latest diablo.
I no longer get any lighting of any sort for diablo. However, overwatch continues to function perfectly.

**Comment by simon-wh** [comment] 2017-07-23 14:59
@Mikewl Did you repatch the wrappers for all the mentioned games?

**Comment by Mikewl** [comment] 2017-07-23 15:03
Yes. Which makes it even more confusing!
I am currently trying with different locations for the wrapper in the d3 folder. Also trying to use the 32-bit version just in case.

**Comment by ersan** [comment] 2017-07-24 08:16
I compiled my own Aurora based on the dev branch (and repatched the wrappers) and this is still a problem for me - the keyboard does not turn red while the game is running, the skill buttons light up and the mouse/mousepad/headset turn red, but the keys do not.  Essentially nothing has changed.

**Comment by simon-wh** [comment] 2017-07-24 13:01
@Mikewl @ersan I'll get the Diablo 3 Starter Edition downloaded to see if I can debug this.

**Comment by Mikewl** [comment] 2017-07-27 15:37
Anything I can do to help this side?
I have vs but I am not sure where to look for the correct values

**Comment by Thelgow** [comment] 2017-11-26 03:00
Just wondering what the status is for the rest of the features?
I just got a Coolermaster Pro L and saw I can do the wrapper feature for Razer, but was let down it didnt have the legendary drop flickering.  
I confirmed on the razer site it says supported features,
Game Effects
    Across all peripherals
        Base colors turn red
        When Dying, peripherals breath red
    Keyboard Effects
        When skills are off cooldown, the keys become white
        Whole keyboard lights up gold upon legendary drop
        Flashes gold quickly upon leveling up
https://www2.razerzone.com/chroma-workshop/integrations-diablo-3-reaper-of-souls
I have a Naga Chroma and can confirm my lights go red on the mouse. Although not sure whats up, exiting the game keeps it red until I do something in Synapse to wake it up.

**Comment by nben** [comment] 2018-01-30 18:48
I've patched the root Diablo III folder with the razer aurora patch, but my keyboard profile stays default (g810). I actually have the default profile disabled, could that be a cause?

**Comment by simon-wh** [comment] 2018-01-30 22:21
@nben Is it the default from LGS?

**Comment by nben** [comment] 2018-01-30 22:27
The profile that remains instead of the diablo lighting is the one from LGS. I have Aurora's desktop profile disabled.

**Comment by simon-wh** [comment] 2018-01-30 23:56
@nben It shouldn't make a difference. Could you check if the wrapper is in the same directory as the game's exe and post your log if that is the case?

**Comment by nben** [comment] 2018-01-31 10:24
The wrapper is in the same directory; here's the log https://pastebin.com/RgsMyUfT
I looked through it briefly and couldn't see any mention of diablo but perhaps there won't be, perhaps it'll just be a mention of razer chroma or something.

**Comment by simon-wh** [comment] 2018-01-31 19:27
I can't see anywhere in the log where it shows that a connection from the wrapper to Aurora has been made, so presumably the wrapper isn't being loaded at all, and if it is it can't connect at all for some reason. Did you apply the wrapper after updating Aurora?

**Comment by nben** [comment] 2018-01-31 19:40
I just reapplied the Razer patch after making sure I'm on the newest dev version of Aurora, but the lighting still doesn't change at all when I load up diablo. I don't need razer synapse installed for this to work through Aurora do I(using a logitech keyboard)?

**Comment by simon-wh** [comment] 2018-02-01 11:12
You shouldn't need to. Could you try enabling the desktop lighting and see if that changes anything? I don't think it should make a difference, but I'm not looking at the code right now so I could be wrong

**Comment by nben** [comment] 2018-02-01 11:54
Enabled desktop profile in Aurora, but Diablo doesn't take control; Aurora's desktop profile keeps running while playing Diablo.

**Comment by simon-wh** [comment] 2018-02-01 16:02
@nben I'm not sure then. I'll get diablo downloaded at some point to try and debug this

**Comment by nben** [comment] 2018-02-01 16:15
Ok, good luck - thanks for the effort so far.

**Comment by diogotr7** [comment] 2018-08-29 18:02
Diablo 3 support has been added alongside changes to the wrapper so it should work. Testing needed.
Build: https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-451/artifacts

**Comment by Funatiq** [comment] 2018-08-30 18:32
Seems to work with my G910. Keyboard lights up red, skill buttons are white and go dark when on cooldown. Sadly I didn't notice any effect for legendary drops.

**Comment by diogotr7** [comment] 2018-08-30 22:29
I'm guessing that issue is something wrong with the in-game support. Can someone with razer devices confirm the legendary drops working?

**Comment by Wizzzzzard** [comment] 2018-09-18 01:50
I have a Razer Chroma Stealth but I'm not sure how to get this working through Aurora, I clicked on Install Aurora wrapper patch for Razer and pointed it to Diablo 3 but it does nothing, the default profile stays active!

The Razer Diablo 3 integration works but it's causing Diablo 3 to throw out an error "error 1016" and kick me back to login screen, this happens after about an hour of gaming and after the first time it keeps happening regularly and only a reboot resets the error back to an hour before it occurs, I was hoping that through Aurora it might not occur.

I would also like to know how to disable the default Aurora profile and use my own desktop profile I created in Razer if possible.

**Comment by diogotr7** [comment] 2018-09-18 14:33
@Wizzzzzard can you try [this](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-482) build that should have native support for it? Please re-check that you applied the patch to the same place the diablo3.exe is in.

**Comment by nben** [comment] 2018-09-27 15:43
hi @diogotr7 I've currently got the latest appveyor build - 0.6.3-494. Diablo is correctly patched, yet there are no keyboard or mouse lights (Logitech G810 and Corsair Sabre)
last night I tried it and it worked once after a sequence of restarts which I can't remember, but it doesn't seem consistent :( the latest log in my folder is here https://pastebin.com/E5Yf3MCf

any ideas?

Cheers
Ben

**Comment by nben** [comment] 2018-09-30 18:57
Okay so slight update - it does seem to be applying the razer wrapper correctly; it's switching to the profile at least, but the keyboard isn't lighting up red at all - so something's wrong with the razer wrapper maybe?

**Comment by diogotr7** [comment] 2018-09-30 19:58
1- Do you have the wrapper layer added to that profile in Aurora?

2- Is there any setting in the game to enable chroma effects?

**Comment by nben** [comment] 2018-10-02 10:21
I found a setting in a config file called DisableChromaEffects, which is set to 0; I'm pretty sure that means effects are enabled. My aurora diablo profile does have a wrapper layer - the preview in aurora is just black, but that's how most of the wrappers are I believe?

**Comment by diogotr7** [comment] 2018-10-02 11:34
Yes. The preview is black until the game sends a command. When the games lighting updates, the preview should, too.

**Comment by nben** [comment] 2018-10-02 15:37
Right - the problem is the game's lighting isn't updating, the keyboard stays black after launch and during play 😢 is this a problem with Diablo maybe?

**Comment by nben** [comment] 2018-10-03 15:49
Is there something that can be fixed in the Razer wrapper to help with this? is that something for simon-wh to look at?

**Comment by diogotr7** [comment] 2018-10-03 16:04
The wrapper was recently improved and a lot of games started working. I didn't see any game stop working with it though

**Comment by nben** [comment] 2018-10-03 17:52
And I saw you put in quite a lot of work to specifically make Diablo III light correctly... I'm not sure what to try

**Comment by diogotr7** [comment] 2018-10-03 18:27
If you want to further debug this it would be best you join the discord. https://discord.gg/YAuBmg9

**Comment by diogotr7** [comment] 2018-10-03 20:53
We concluded that the game won't load the Razer wrapper dll if CUE is open, as the game has support for both. If you have issues try closing CUE (or not using aurora for this game if you have corsair hardware).

**Closed by diogotr7** 2018-10-03 20:53 UTC
Labels: bug
