### ISSUE TITLE
Log files created taking up hundreds of GB, General performance issues

### ISSUE THREAD

**Issue by tommy7373** [antonpup/Aurora#1127] opened 2018-06-09 01:07 UTC
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [x] Other, (Log file creation and size)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Log file size)

### Expected behavior:
Prior to an Aurora update, the program's performance was normal, and no log files were seen (at least not large enough to see).

### Actual behavior:
At the desktop and in Overwatch (using G810 with Razer patch), any effects shown on the KB stutter, and often freeze a few times a second. Log files are being generated taking up tens of GBs per day.

### How often does this problem occur?
All the time, whenever Aurora is running.

### Please describe the steps to reproduce this issue:
Simply running Aurora will cause the log files to grow. 

### What is the version of Aurora you are experiencing this issue with?

My current version is 0.6.1 dev4

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0b), did not have this issue.
However, I have tried to revert to the old version and create new profiles from scratch, but the issue still persists even if I go back to an older version.

### Please include any logs, screenshots, or files that are related to this issue:
Log files in AppData/Roaming/Aurora/Logs are all too large to show or upload. Log files since 5/20/18 are 123GB.
![image](https://user-images.githubusercontent.com/21339116/41186147-31fd58c6-6b57-11e8-8a97-8fdc7ea2b8a5.png)

The log files seem to be repeating this error:

> [ERROR] 19:59:27: Exception: System.TypeInitializationException: The type initializer for 'Aurora.Profiles.LocalPCInformation' threw an exception. ---> System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName)
   at Aurora.Profiles.LocalPCInformation..cctor() in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\GameState.cs:line 205
   --- End of inner exception stack trace ---
   at Aurora.Profiles.LocalPCInformation..ctor() in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\GameState.cs:line 232
   at Aurora.Profiles.GameState`1.get_LocalPCInfo() in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\GameState.cs:line 58
   at lambda_method(Closure , GameState )
   at Aurora.Utils.GameStateUtils.RetrieveGameStateParameter(IGameState state, String parameter_path, Object[] input_values) in C:\projects\aurora\Project-Aurora\Project-Aurora\Utils\GameStateUtils.cs:line 140

**Comment by simon-wh** [comment] 2018-06-19 11:39
For the error that is being spammed, please try the solution mentioned here: https://stackoverflow.com/questions/17980178/cannot-load-counter-name-data-because-an-invalid-index-exception

For the large log files, duplicate of #1065

**Closed by simon-wh** 2018-06-19 11:39 UTC
