### ISSUE TITLE
Away Effects don't trigger anymore

### ISSUE THREAD

**Issue by NuclearMeltdown** [antonpup/Aurora#44] opened 2016-06-18 20:04 UTC
They simply don't trigger anymore when the set time passed. Not even setting the delay to 0 triggers them immediately, even though they should.

**Comment by smh51** [comment] 2016-06-18 20:06
Same issue here

**Comment by antonpup** [comment] 2016-06-18 20:08
How long have you been running Aurora for? Approx how much of that time has computer been Idle for Aurora's away effects to actuate? What games were played prior to this discovery?

**Comment by NuclearMeltdown** [comment] 2016-06-18 20:12
I first noticed that yesterday and I thought it was because it hung up somewhere. But now I came home shortly before I tested this, so the program was running for a few minutes and no games were being played before this.

**Comment by antonpup** [comment] 2016-06-19 03:49
I will look at this issue after I finish the profile import/export.

**Comment by antonpup** [comment] 2016-06-20 20:45
Confirmed not working. Will be fixed in the next version.

**Comment by antonpup** [comment] 2016-06-21 07:41
Fixed in the next version. Issue was caused by Skype Overlay, disabling it returns the Away Effects functionality.

**Closed by antonpup** 2016-06-21 07:41 UTC
Labels: bug
