### ISSUE TITLE
Corsair K95 Platinum M1,M2,M4 and M5 Not working.

### ISSUE THREAD

**Issue by thehunterdante** [antonpup/Aurora#1635] opened 2019-07-17 23:53 UTC
[2019-07-17 18.13.02.log](https://github.com/antonpup/Aurora/files/3404164/2019-07-17.18.13.02.log)
[2019-07-17 18.21.47.log](https://github.com/antonpup/Aurora/files/3404165/2019-07-17.18.21.47.log)
[2019-07-17 20.06.05.log](https://github.com/antonpup/Aurora/files/3404166/2019-07-17.20.06.05.log)
[2019-07-17 20.25.57.log](https://github.com/antonpup/Aurora/files/3404167/2019-07-17.20.25.57.log)

### Actual Behaviour
Well, first I downloaded the aurora software and installed it like every program, then I just followed every step shown on the programm guide to synchronize my K95 Platinum keyboard with icue and aurora, everything was going okay until I noticed that theese macros (1,2,4,5) didn't work, they only lighted up when I changed the profile in aurora,  like K95 o Logitech keyboards with these macros, I tried everything, changed the language, reinstall the program, install every patch from the program that comes with it but nothing worked as you can see my issue is shown on the pictures

### Reproduction steps
Download aurora software, install it, config the program as the guide on it says, have a Corsair K95 Plat Keyboard

### Frequency
Always

### Aurora Version:
0.6.4b

### Previously an Issue?
 First time using this software

Images:
![bnj](https://user-images.githubusercontent.com/7144667/61419508-ec26a700-a8d4-11e9-9dab-d48e260efb8d.PNG)
![terter](https://user-images.githubusercontent.com/7144667/61419509-ec26a700-a8d4-11e9-97f4-51e108594d22.PNG)
![WhatsApp Image 2019-07-17 at 20 26 32](https://user-images.githubusercontent.com/7144667/61419510-ec26a700-a8d4-11e9-8d4a-69ba93ffd5b3.jpeg)
![WhatsApp Image 2019-07-17 at 20 26 44](https://user-images.githubusercontent.com/7144667/61419511-ec26a700-a8d4-11e9-9c91-f96c848d8222.jpeg)

**Comment by diogotr7** [comment] 2019-07-17 23:56
Duplicate of #1620

**Closed by diogotr7** 2019-07-17 23:56 UTC
Labels: bug
