### ISSUE TITLE
MK750 already supported?

### ISSUE THREAD

**Issue by Junneh** [antonpup/Aurora#1047] opened 2018-04-01 21:55 UTC
I would like to ask if the MK750 from Coolermaster is already supported before buying it. Maybe it works through the MK PRO L wrapper? Afaik the led controller is the same, it just has addeds light bars.

If anyone can chime in on this, please do!

**Comment by MithicalM** [comment] 2018-04-02 17:21
https://github.com/antonpup/Aurora/issues/1014 He is working on it. I have the keyboard and its working for the most part so far. Just some keys don't light up at the moment and the lights are slightly misaligned. Once that is fixed it should be all good.

**Comment by Junneh** [comment] 2018-04-02 18:38
thanks for the response!

**Comment by simon-wh** [comment] 2018-05-02 09:01
Duplicate of #1014

**Closed by simon-wh** 2018-05-02 09:01 UTC
