### ISSUE TITLE
K70/K70 Lux RGB Media Keys

### ISSUE THREAD

**Issue by SkyLegendary** [antonpup/Aurora#199] opened 2016-11-03 00:11 UTC
Media key lights on my K70 LUX RGB keyboard don't work. Not sure if it's just not implemented yet or if I'm too blind to find the media key implementation already there. 😋

**Comment by brainbug89** [comment] 2016-11-03 12:09
Duplicate of #126 fixed on dev branch

**Closed** 2016-11-29 14:46 UTC
