### ISSUE TITLE
Support for Corsair H115i , MSI B360 & Aorus Gigabyte 1080Ti 

### ISSUE THREAD

**Issue by SirHeadSh0t** [antonpup/Aurora#1100] opened 2018-05-16 11:49 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Corsair H115i)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:

- Corsair H115i CPU Cooler should light with the keyboard &/or Mouse Headset Peripherals. 
- If possible to add support for the MSI B360 Using Mystic Light App for mobo RGB & Fan RGB)
- If possible to add support for Gigabyte Aorus 1080Ti using Aorus Graphics Engine for RGB Control

Note: I cannot find any SDK settings in the MSI or the Aorus Software

### Actual behavior:
As Aurora takes control of the Corsair SDK The CPU Cooler lights go off completely.

### How often does this problem occur?

This problem occurs... (Every Time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1-dev4)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
I cannot find the log location at Aurora Location./logs , only an Nlog Config file.

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

Note of Thanks: 
Thank you for your continued support of the Aurora application , i have been using it for about 2 years now and it is just great.
Many thanks ,your work is much appreciated.

If there is anyway I can help please let me know :)

**Comment by BranWar** [comment] 2018-05-16 21:45
Yeah, all my fans and lighting strips go rainbow when I play GTA V, so It'd be really cool if we could get support for other devices. I would try myself, but I am an absolute coding idiot.

**Comment by simon-wh** [comment] 2018-05-29 13:44
Corsair is Duplicate of #1055 
MSI is Duplicate of #642 
Gigabyte is Duplicate of #873 

I plan to add support for these with the big redesign I'm planning which will allow for proper lighting of devices that are not just Keyboards + Mice

**Closed by simon-wh** 2018-05-29 13:44 UTC
