### ISSUE TITLE
Rocket league is no longer supported?

### ISSUE THREAD

**Issue by imatowel** [antonpup/Aurora#994] opened 2018-02-25 15:13 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [x ] Aurora supported game, Rocket League
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, Rocket league had an update recently for the new season so I believe the pointers just need updating? 

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, not working at all 

### Expected behavior:
should have blue and red keyboard for teams, boost indicator etc

### Actual behavior:
keyboard just sits there blue

### How often does this problem occur?

This problem occurs all the time every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. launch rocket league
2. look at keyboard
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... latest public built as of 25/02/2018

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2018-02-25 15:23
Duplicate of #185

**Closed by simon-wh** 2018-02-25 15:23 UTC

**Comment by imatowel** [comment] 2018-02-27 19:40
Hello,

Still cant get it to work on my logitech g910? Have reinstalled software
deleted profiles and used the default stock ones, am i missing anything?

**Comment by simon-wh** [comment] 2018-02-28 15:00
@imatowel See #185, it is currently still broken as the pointers haven't been updated yet.

**Comment by Rechinan** [comment] 2018-03-06 00:04
Looking forward to the update, i play rocket league almost everyday and this will complime it well

**Comment by CounterSteins** [comment] 2018-04-27 13:33
Any news here ? iam loving the ingame features of Aurora and the missing Rocket League integration is my only concern so far. Would love to have this working! Keep up your great work

**Comment by simon-wh** [comment] 2018-05-05 15:42
@CounterSteins I don't have the time right now to update the pointers. The main problem is that when the game updates they have to be found again. I have exams coming up right now so I don't have the time to sort it.

**Comment by CounterSteins** [comment] 2018-05-05 17:51
Duden dont worry. Ich have exams in university too. It is The priority!
Good luck!

Simon W <notifications@github.com> schrieb am Sa., 5. Mai 2018, 17:42:
