### ISSUE TITLE
Please add support for Tom Clancy's Rainbow Six Siege

### ISSUE THREAD

**Issue by nyan257** [antonpup/Aurora#317] opened 2017-01-04 10:58 UTC
Title

**Comment by brainbug89** [comment] 2017-01-04 13:45
Duplicate of #163 and #92
Seems to be not possible.

**Comment by antonpup** [comment] 2017-01-04 17:58
I have bought R6Siege, so I will see if logs can provide some useful information.

**Comment by simon-wh** [comment] 2017-03-20 08:32
Duplicate, closing

**Closed by simon-wh** 2017-03-20 08:32 UTC
Labels: duplicate, enhancement, game support
