### ISSUE TITLE
German Layout on Corsair Keyboards

### ISSUE THREAD

**Issue by grimsi** [antonpup/Aurora#203] opened 2016-11-05 18:29 UTC
If you choose German Keyboard Layout in the menu it displays the right layout in the preview, but the "Z" and "Y" keys are still swapped on my Keyboard (Corsair K70 LUX RGB).

**Comment by brainbug89** [comment] 2016-11-06 15:50
Duplicate of #123

**Comment by santosch** [comment] 2016-11-10 19:27
I can confirm this with Corsair K95 RGB

**Closed** 2016-11-29 14:17 UTC
