### ISSUE TITLE
Rocket League w/ Strafe

### ISSUE THREAD

**Issue by Mowgli1** [antonpup/Aurora#1545] opened 2019-04-19 01:10 UTC
### Expected behavior:
The lights should turn on and it should work

### Actual behavior:
No lights turn on at all, not even on the desktop

### How often does this problem occur?
Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.Launch Aurora and the keyboard goes dark
2.Select Rocket League
3. Open it through steam

### What is the version of Aurora you are experiencing this issue with?
My version is 6.4b

**Comment by diogotr7** [comment] 2019-04-20 23:03
Duplicate of #185

**Closed by diogotr7** 2019-04-20 23:03 UTC
