### ISSUE TITLE
Request support for Cooler Master Masterkeys Pro M RGB

### ISSUE THREAD

**Issue by Firedrops** [antonpup/Aurora#788] opened 2017-09-13 03:36 UTC
I see support for L and S, but no M. Does it share the same SDK?
(http://makerhub.coolermaster.com/custom-lighting/)

**Comment by brainbug89** [comment] 2017-09-13 15:03
Duplicate of #603 

I already added it here: #608 

Try the latest dev version: https://github.com/antonpup/Aurora/releases/tag/v0.6.1-dev3

**Closed** 2017-09-13 15:07 UTC
