### ISSUE TITLE
Rocket League Support

### ISSUE THREAD

**Issue by MustacheNL** [antonpup/Aurora#827] opened 2017-10-07 12:44 UTC
### What are you experiencing an issue with?

- [ ] Aurora
- [X] Aurora supported game, Rocket League
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Other, lightning doesn't work!

### Expected behavior:
The lights should work in Rocket League

### Actual behavior:
Background only shows blue!

### How often does this problem occur?
Every time!

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Installs Aurora
2. Starts Rocket League, plays game, doesn't work.

### What is the version of Aurora you are experiencing this issue with?

Beta v.0.6.0b

### Does the previous version of Aurora have this issue?
Don't know.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment] 2017-10-07 18:00
Duplicate of #185

**Closed by simon-wh** 2017-10-07 18:00 UTC
