### ISSUE TITLE
Logitech LED SDK games wont work (Battlefield 1, The Division)

### ISSUE THREAD

**Issue by karabin1000pl** [antonpup/Aurora#1428] opened 2019-02-04 01:42 UTC
### How often does this problem occur? 

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Ghub and Aurora
2. Launch Battlefield 1 or The Division
3. Your rgb lighting wont work

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.4b

### Does the previous version of Aurora have this issue?
The previous version 0.6.4 have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
[2019-02-04 02.34.30.log](https://github.com/antonpup/Aurora/files/2826249/2019-02-04.02.34.30.log)

**Comment by Wibble199** [comment] 2019-02-12 14:59
Have you applied the Logitech patch?

**Comment by karabin1000pl** [comment] 2019-02-12 16:00
Yes i applied Logitech patch and it still wont work also after few days i have another issue with Aurora, now it wont init logitech LED SDK in any game (Euro Truck Simulator 2, Diablo III , Overwatch)etc. 
[2019-02-12 16.58.56.log](https://github.com/antonpup/Aurora/files/2856546/2019-02-12.16.58.56.log)

**Comment by karabin1000pl** [comment] 2019-03-01 14:34
I managed to fix not working Aurora but still Logitech LED SDK games wont work.
My steps:
1.Uninstall Aurora
2.Uninstall GHUB
3.Reboot PC
4.Install GHUB
5.Reboot PC
6.Install Aurora
7.Reboot PC
8.Go into GHUB settings and enable and disable aurora.exe serveral times.
9.Launch Aurora and turn off desktop lighting then turn it on.
10.Now i can use Aurora RGB lighting in overwatch, Diablo III, Euro Truck Simulator 2 but games which require Logitech LED SDK(The Division, GTA V, Battlefield 1) still wont work

**Comment by c1tru55** [comment] 2019-03-03 16:43
doesn't work for me also in GTA 5, Battlefield 1

**Comment by sausje** [comment] 2019-03-05 01:04
> but games which require Logitech LED SDK(The Division, GTA V, Battlefield 1) still wont work

I had the same issue, but this is because I had set a persistent profile in G HUB. Once I put that to "none" G HUB could take over from Aurora with the correct Logitech profile for that game.

Hope that fixes the issues you guys are having.

**Comment by karabin1000pl** [comment] 2019-03-05 02:31
Thanks for your response @sausje 
In my ghub i had "none" profile but i switched into persistent then switched again into "none" and now it works, thank you very much!!!!! Battlefield 1 and The Division lighting works now but GTA V lighting still wont work i think reason for this is that GTA V is not detected by ghub i will try to reinstall GTA V and i will let you know if it works

**Comment by KaHonu** [comment] 2019-08-15 15:33
@Wibble199 

I just determined using only Logitech hardware that the GTA V problem is likely related to GHUB. If you install the latest version of Logitech Gaming Software (LGS) GTA V lighting works fine. This was tested with Aurora shut down. It's very likely that if you have Aurora running and use the wrapper + LGS it will work again.

Do some Googling and you will find that people with Logitech hardware that don't use Aurora have complained that GTA V works fine with LGS but is broken with GHUB. This appears to be an issue with GHUB and not Aurora + Logitech wrapper. If others can verify that 'downgrading' to LGS resolves issues noted above for other games this should probably be closed.

**Comment by diogotr7** [comment] 2019-08-15 19:52
The aurora patch isn't fully working either, the registry patch isn't applied correctly. When the fix is merged, it should work correctly regardless if g hub is installed or not. 
Another separate issue for gta v is that the hardcoded colors in Aurora are outdated and some of them are not correct anymore.

I can confirm that with the fix gta v and bf1 are both working in my wooting one.

**Comment by diogotr7** [comment] 2019-11-15 10:23
The registry patch was fixed with v0.7.0 i believe, please make a new issue if it still persists.

**Closed by diogotr7** 2019-11-15 10:23 UTC
Labels: bug, feedback needed
