### ISSUE TITLE
Razer + Philips Hue

### ISSUE THREAD

**Issue by Nitzowsky** [antonpup/Aurora#945] opened 2018-01-09 07:30 UTC
There ia a way to implement this new system from Razer?

https://www.razerzone.com/gaming-accessories/philips-hue

**Comment by cubeslice** [comment] 2018-01-21 20:34
Yes, that would be pretty awesome.

**Comment by wanildopneto** [comment] 2018-02-02 20:53
Agreed.

**Comment by simon-wh** [comment] 2018-02-14 13:03
Duplicate of #358

**Closed by simon-wh** 2018-02-14 13:03 UTC
Labels: enhancement, sdk support
