### ISSUE TITLE
Using Layer as "Away Effect"

### ISSUE THREAD

**Issue by rojnwa** [antonpup/Aurora#1248] opened 2018-09-07 12:27 UTC
Hey there,

is there a way to use layer (e.g. "Ambient Layer") as Away Effect?

Kind regards

**Comment by Soulshake1** [comment] 2018-09-16 19:18
Nice ! With Layers possible in Away Effect, I could finnaly add audio layer with a deylay of 5 mins to sync it with plane9 my screensaver that also supports audio in its effects, GREAT !! cant await THX

**Comment by xQwexx** [comment] 2020-01-03 10:48
Duplicate of #768

**Comment by diogotr7** [comment] 2020-01-03 13:54
This is now doable with overrides.

**Closed by diogotr7** 2020-01-03 13:54 UTC
Labels: Type: Enhancement
